### ISSUE TITLE
Input invisible on macos

### ISSUE THREAD

**Issue by theovosse** [wxMaxima-developers/wxmaxima#1046]
I've just now installed maxima and wxmaxima (v. 18.02.0) via brew on MacOS 10.14. When I start wxmaxima, I can't see what I'm typing: it seems partially obscured by a white rectangle overlaying the input area. You can see what 'x^2 - 1 = 0 in a new window and what solving it for x looks like in the attached screen shots

.
![screen shot 2018-11-04 at 10 13 52](https://user-images.githubusercontent.com/16035872/47962273-4b2be080-e012-11e8-88ac-b4d299b1699b.png)
![screen shot 2018-11-04 at 10 15 43](https://user-images.githubusercontent.com/16035872/47962274-50892b00-e012-11e8-969f-73c2f5cfa456.png)

**Comment by gunterkoenigsmann** [comment]
For 18.10 I have redesigned the display routines in order to fix Mac problems (I don't own one so all I can do is to look at the source and to try to find hints in the big reports where the problem can lie.

Missing input, though, seems to point to the color of the input being sent to something like "Black, 100% transparent" or similar...

**Comment by theovosse** [comment]
In the first screen shot, you can see the "- 1", so it's only the prompt and 'x^2 that's hidden, so the color is not 100% transparent. It looks like a rectangle is overlapping the cell region. Below it, another rectangle (with an outline) is visible.
