### ISSUE TITLE
wxMaxima, wrong formating of upper index in graph legends

### ISSUE THREAD

**Issue by mirekslouf** [wxMaxima-developers/wxmaxima#1063]
Current nighly-build of wxMaxima (downloaded 2018-12-01) in my computer (Windows 7, Maxima version: 5.41.0a_dirty) shows wrong formatting of upper index in the graph legends:

* Error description: in the graph legends showing the expressions like x**0.5, only the first character [0] is uppercase, the rest is standard font.
* The formatting error appears both in WXMX files and PDF files.
* See the attached PDF: [test_graph.wxmx.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/2635872/test_graph.wxmx.pdf)

**Comment by gunterkoenigsmann** [comment]
The indices in graphs are drawn by ghostscript which has a more TeX-like syntax than Maxima: Everything that is to be displayed as a super- or subscript needs to be enclosed in curly brackets:

     wxdraw2d(
         grid=true,
         key="sin_{Test}^{test2}",
         explicit(sin(x),x,1,10)
     );

There might be a way to teach maxima to set the default plot label in a way that it is printed out correctly in gnuplot. But this would require a feature request to http://maxima.sourceforge.net instead as wxMaxima is only involved in displaying the picture, but not in creating it.

Will close this comment, not because the current behaviour cannot be improved, but, because it is better improved in a different project.
