### ISSUE TITLE
tentex() swaps indices in itensor::levi_civita()

### ISSUE THREAD

**Issue by BwanaTheBig** [wxMaxima-developers/wxmaxima#1071]
kill(all)$
	load(itensor)$
	imetric(g)$
	idim(3)$
	load(tentex)$

	Aij:ishow('levi_civita([i,k,j],[])*u([-k],[]))$
(Aij)	levi_civita[i **k** **j**]*u^k
	tentex(Aij);
$$\varepsilon_{i\,**j**\,**k**}\,u^{k}$$
	Bij:ishow('levi_civita([i,k,j],[])*u([],[k]))$
(Bij)	u^k*levi_civita[i **k** **j**]
	tentex(Bij);
$$\varepsilon_{i\,**j**\,**k**}\,u^{k}$$

**Comment by gunterkoenigsmann** [comment]
That looks like a bug in maxima, the program that does the actual maths: wxMaxima seems to only display the result in this case => Would you be so kind and report it to http://maxima.sourceforge.net/ ?

Will close this ticket for wxMaxima, not because I believe it not to reflect an actual bug, but because it is better resolved in a different project.
