### ISSUE TITLE
plot2d([parametric, ...]) values clipped if not parameter t used

### ISSUE THREAD

**Issue by csae7255** [wxMaxima-developers/wxmaxima#1097]
The command 
plot2d([parametric,sin(x),cos(x),[x,0,2*%pi]])
plots only the values for x=0..%pi and gives the message: Some values were clipped, back

using 
plot2d([parametric,sin(t),cos(t),[t,0,2*%pi]])
works fine!

On Windows 10, Maxima Version 17.10.01

**Comment by gunterkoenigsmann** [comment]
Often it is hard to tell. But this time this is a problem in maxima that does execute most commands, not in wxMaxima whose main task is to display the results => would you be willing to report it to https://maxima.sourceforge.net? Thanks in advance!

Will close this ticket for wxMaxima - not because I am not interested in what has happened, but because it is better dealt with in the other project.
