### ISSUE TITLE
wxMaxima 19.04.1 doesn't redraw worksheet correctly

### ISSUE THREAD

**Issue by justdanyul** [wxMaxima-developers/wxmaxima#1110]
I got a big problem with wxMaxima on Linux. 

Basically, the worksheet seems all over the place. It will flicker between the state seen in the screenshot below and a state where at least the background of the sheet is consistently white. Menus and other things will not get cleared and tattooed on the top of the worksheet. And even worse, it only renders part of the worksheet. Meaning, half the worksheet in the picture attached, is never rendered. 

![1555622501](https://user-images.githubusercontent.com/13814798/56392138-86b91080-6228-11e9-9f13-fb81fe0fb6d9.png)

**Comment by gunterkoenigsmann** [comment]
Wow... ...this looks bad. But isn't reproducible on my computer.
My guess therefore is that this problem is specific to one graphics driver, windowing system (X11R6/Wayland/Unity) or wxWidgets version.

In theory wxWidgets is informed which part of the window needs to be redrawn, informs wxMaxima about that. wxMaxima then redraws the part of the worksheet it needs to redraw - and everything should be fine.

That means: How did you get the background colour to be navy blue? That might be a hint...

**Comment by justdanyul** [comment]
This is a fresh install of wxMaxima, straight from the package manager in the distro I use. The colors are inherited from my GTK theme (Adapta-Nokto), I've tried multiple other themes though, including the gnome default Adwaita, and the problem persists.

I've also tried other windows managers and desktop environments, and it's all the same. I'm on X, Nvidia closed source drivers and wxWidgets 3.0.4. Personally, I suspect its the latter causing the issues.

**Comment by gunterkoenigsmann** [comment]
Or it is the Nvidia drivers in combination with wxWidgets 3.0.4: wxWidgets 3.0.4 together with intel are fine.

With a bit of luck the wxMaxima from https://code.launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies/ works better: The current nightly builds use a different method of redrawing the worksheet. Wouldn't be the first time that such a change by chance works around a bug...

**Comment by justdanyul** [comment]
Thanks for the tip, and for trying to help.

I tried building out master myself (as I'm not on a deb friendly distro), unfortunately, it didn't make a difference.

**Comment by justdanyul** [comment]
Hello again,

I tried building out your speculative go, unfortunately, it didn't fix the issue. However, I tried linking against wxgtk2 instead of wxgtk3, and this fixed the problem.

**Comment by gunterkoenigsmann** [comment]
Then thanks for the hint. Will test gtk3+intel tomorrow.

**Comment by jose-matos** [comment]
I seeing something like this but the point is that I am using a dark theme. Placing the cursor above the text renders background colour to white and then it is normal.

**Comment by gunterkoenigsmann** [comment]
In the meantime I've changed many of the display routines hoping to fix similar bugs. With a bit of luck that accidentally has fixed the nVidia problem, as well.
---
Since Apple offers a dark mode, too: What is expected to happen in this case? Should the worksheet background get dark in dark mode and the foreground colors that are too similar to the dark background be inverted? Or should the worksheet stay black letters on a white background? I guess the latter is true as I don't expect MS Word, Writer, Openoffice or Excel to write white on black paper.

**Comment by gunterkoenigsmann** [comment]
Arrgh! Additionally to the horizontal line I intended I got giant bold letters. Sorry for that.
