### ISSUE TITLE
Output rendering and interaction problems

### ISSUE THREAD

**Issue by ian11213** [wxMaxima-developers/wxmaxima#1119]
In my hands under Arch linux+xfce on a Samsung NP300E5C laptop, the interface becomes progressively unusable after evaluation of a few cells. The cursor fails to respond to arrow keys, and a mouse click places the cursor several lines above the pointer position (often outside the visible portion of the window). Rendering of output becomes uncertain, with equations appearing "eventually" - initially incomplete. The problem seems to be common to the 19.mm.nn packages; downgrading to 18.11.1 solves all these issues.
The problem does not seem to relate to any particular symbol set or calculation type.

**Comment by gunterkoenigsmann** [comment]
The problem was that for determining what to draw and what is drawn where the scrolling was applied twice - but for some reason not on Ubuntu (which is the Linux distribution I am using).

On the plus side ArchLinux has an excellent maintainer for wxMaxima and very helpful testrs which means that the fix will be ported to ArchLinux as soon as possible.

If everything works out on Ubuntu and on Windows, too, I will make a new wxMaxima release tomorrow.

**Comment by gunterkoenigsmann** [comment]
Officially released the updated version now.
