### ISSUE TITLE
Feature Request: Center Output Cells

### ISSUE THREAD

**Issue by jIyajbe** [wxMaxima-developers/wxmaxima#1133]
Is it possible to center-justify the tex-formatted output in %o output cells? This would make the document look more like what you typically see in textbooks and published papers.

(Perhaps make it a preference item?)

Thanks for considering it!

**Comment by gunterkoenigsmann** [comment]
I seem to remember that either a includepackage command or a parameter in the Tex preamble makes them left aligned...

**Comment by gunterkoenigsmann** [comment]
I think I found it: If you remove the "[fleqn]" from the \documentclass command the equations are centered. Will make the [fleqn] optional.

**Comment by jIyajbe** [comment]
Excellent! I really appreciate you not forgetting about this among more important issues. --And, ah, can you tell me where to find the \documentclass command?

**Comment by gunterkoenigsmann** [comment]
You are welcome ;-) Took me a while to find out where the problem lies, though...
The command should be in the first line of the TeX document wxMaxima exports. In the next nightly build of wxMaxima the command should be editable in wxMaxima's config dialogue by changing the entries "documentclass" and "documentclass options".

**Comment by jIyajbe** [comment]
That did it! Great!!
--Oh, and btw: on my macOS installation, 18.10.1, the parameter in the \documentclass[] command is "leqno", not "fleqn".

At the risk of getting greedy...Is there a way to get the output equations centered in the wxMaxima application window?
