### ISSUE TITLE
When animated plot is selected, scroll wheel scrolls both animation time and document position

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1134]
Dear wxMaxima Team,

when an animated plot is created with `wxanimate_draw` and the plot is selected, moving the mouse scroll wheel moves both, the window position and the time of the animation window.

This is the same as #436. It was fixed but with recent nightly builds this issue came back.

Best regards,

Michael

```
wxMaxima version: 19.05.5
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_42_base_724_g3ccc201c0
Maxima build date: 2019-05-23 23:46:33
Host type: x86_64-w64-mingw32
System type: Win32 10.0.16299 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.14
wxMaxima's idea of the directory layout is:
User configuration dir: C:/Users/soegtrop/maxima/
Help dir: C:\bin\maxima-current-2019-05-24\wxMaxima/help
```

**Comment by gunterkoenigsmann** [comment]
Currently there is no way to hinder Windows from scrolling the worksheet when the worksheet receives a scroll event. If an animation should receive the scroll event instead I therefore simulate a click on the animation slider. Which means that this slider receives the scroll events.

Normally this works fine. The only place I know this fails is if one uses an extension that makes windows send scroll events to the object the mouse pointer is over instead of to the object that is currently selected. Don't know if you have such a thing installed, though...
