### ISSUE TITLE
Trend Mirco Security does not like Wxmaxima.exe encryption.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1172]
My company started using Trend Micro Security.   It does not seem to like WxMaxima, because it thinks it has some unauthorized encryption.  Does it use encryption?  I put an exception on the maxima-current and the bin folder and also on the file wxmaxima.exe and it still quarantines the program when I run it.
![image](https://user-images.githubusercontent.com/31253976/68901223-1f4e3b00-06fb-11ea-8e8d-07b65d1ed6ad.png)

**Comment by gunterkoenigsmann** [comment]
wxMaxima doesn't use any encryption - even if I would welcome having a possibility to use https in order to check for updates or to encrypt the communication with maxima - just because everything is encrypted nowadays. Would you mind submitting a false-positive issue to TrendMicro? I believe such a thing being descried in https://success.trendmicro.com/solution/1119869-reporting-a-false-positive-issue-in-deep-security

**Comment by gunterkoenigsmann** [comment]
What wxMaxima does do is to scan the maxima directory for loadable share and demo files. Perhaps trendmicro mistakes that for preparing to encrypt the files later - and wxMaxima contains the bitmaps for the toolbar and the startup commands that teach maxima to talk in XML. It uncompresses all of these pieces of information when they are needed. Perhaps TrendMicro believes the standard uncompressor to be used in a strange way. But storing them uncompressed in memory somehow triggers strange bugs in some compilers that even in 2019 aren't prepared to deal with chunks of user data that are tens of kilobytes big. Which caused bugs that were hard to hunt down...

**Comment by richardgobeli** [comment]
Today Trend Micro has made a change that it now does not quarantine the WxMaxima.exe file.  So it is now OK.   The exception I installed only stopped the scanning of the program file.  I think the change today also stopped Trend Micro from scanning the running program.
