### ISSUE TITLE
draw2d does no longer show polar grid.

### ISSUE THREAD

**Issue by XaoDefyMi2** [wxMaxima-developers/wxmaxima#1173]
I have a document created with wxMaxima 16.04.2 with an example of 2D polar plot, wich produced:
![OK](https://user-images.githubusercontent.com/7250523/69076557-0794f080-0a34-11ea-8140-9407ac570ec2.png)

Now with wxMaxima 19.09.0 (maybe earlier versions too) the grid is always rectangular:
![NOT_OK](https://user-images.githubusercontent.com/7250523/69076703-4f1b7c80-0a34-11ea-9ed4-d028fec4bf08.png)

I'm not sure if it is wxMaxima realted or some change in Gnuplot, but in a Gnuplot console with 'set polar' and 'set grid polar' the polar grid shows correctly.

I'm on:
Arch Linux x86_64
![imagen](https://user-images.githubusercontent.com/7250523/69077436-ed5c1200-0a35-11ea-89f1-67242c222ac7.png)

**Comment by gunterkoenigsmann** [comment]
ArchLinux is good news since they tend to update their software frequently. The bad news is that the problem this time lies in maxima (https://maxima.sourceforge.net) and not in wxMaxima so I cannot help you this time even if this bug report is friendly and complete. Would you be willing to report it to the maxima project team? I'll close the ticket for wxMaxima, not because it is invalid or because the bug doesn't look like it were in wxMaxima, but because it has to be solved in an external project.

**Comment by XaoDefyMi2** [comment]
I created a ticket at [https://sourceforge.net/p/maxima/bugs/3595/] as you sugested. I should have tested in Maxima before opening this issue. Thank you very much @gunterkoenigsmann!

**Comment by gunterkoenigsmann** [comment]
No complaints from my side: Testers are important - and if someone has to feel kind of guilty it is me who had to sent you to another project after you investigated the problem and had written a friendly bug report that was more complete than any project leader can expect. also even if I know that maxima is split in front- and backend I often initially get the info wrong which project a problem actually has to be resolved in.
