### ISSUE TITLE
The presuperscript and postsuperscript do not seem to work.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1186]
![image](https://user-images.githubusercontent.com/31253976/71144978-83c25580-21e5-11ea-808d-664477260c97.png)
![image](https://user-images.githubusercontent.com/31253976/71145005-9472cb80-21e5-11ea-93dd-3a9af5a9dc4e.png)
![image](https://user-images.githubusercontent.com/31253976/71145026-a05e8d80-21e5-11ea-9449-3583028b01f9.png)
![image](https://user-images.githubusercontent.com/31253976/71145031-a7859b80-21e5-11ea-9d17-4fef3eec64b8.png)
![image](https://user-images.githubusercontent.com/31253976/71145039-b2403080-21e5-11ea-9d96-82d656e0eac4.png)
![image](https://user-images.githubusercontent.com/31253976/71145043-b8361180-21e5-11ea-9929-363e070668d5.png)
![image](https://user-images.githubusercontent.com/31253976/71145052-bec48900-21e5-11ea-85ae-a891b99de171.png)

Check how the manual shows the result.

**Comment by gunterkoenigsmann** [comment]
The C++ part of making them work has already been done. But for the lisp part I would need a skilled lisp programmer that I currently don't have at hand.

**Comment by richardgobeli** [comment]
Does this mean there needs to be lisp functions done in Maxima?

**Comment by gunterkoenigsmann** [comment]
wxMaxima at startup sends a block of lisp commands to maxima that teach it to talk in a XML  dialect in order to inform wxMaxima not only how maxima:s output looks like bit also what it means and what maxim commamds could be used to produce exactly this subscripted variable name.
What is needed now is to extend this block of lisp code with code that sends the right XML items if maxima encounters the pre/post subscript properties. What is currently sent to maxima can be read here: https://github.com/wxMaxima-developers/wxmaxima/blob/master/data/wxMathML.lisp

**Comment by robert-dodier** [comment]
@gunterkoenigsmann About the XML formatting needed for pre/post sub/superscripts, do I understand correctly that what's needed is to generate MathML expressions as described on this page: https://www.w3.org/TR/REC-MathML/chap3_4.html 

If so, I think it would be relatively straightforward to write the code for that ... There are functions in the Maxima display code to sort out which indices go in each position. Those can be called and then the XML generated according to what is returned for each position. You can let me know what you think about that.

**Comment by richardgobeli** [comment]
There also needs to be a way to do the sub and super scripted without commas for displaying tensor indices that have position like the following:
![image](https://user-images.githubusercontent.com/31253976/71317913-896ea400-244e-11ea-856d-ae1e9b7fdfdc.png)
Currently itensor uses array sub-scripts and exponent for super-scripting.   Mathematically the position is lost.

**Comment by gunterkoenigsmann** [comment]
@robert-dodier :  https://github.com/wxMaxima-developers/wxmaxima/blob/master/data/wxMathML.lisp --- I guess for historical reasons --- uses different tag names to https://www.w3.org/TR/REC-MathML/chap3_4.html in some cases. For example `<mrow>` was always named `<r>`. Ever since I've found out that I wanted to clean up this by making wxMaxima both accept the old wxMaxima tag names and the "real" MathML tag names. Today I have started to do that with making https://github.com/wxMaxima-developers/wxmaxima/blob/master/data/wxMathML.lisp use `<mrow>` instead of `<r>` and making wxMaxima understand that, too.

if you would be willing to modify https://github.com/wxMaxima-developers/wxmaxima/blob/master/data/wxMathML.lisp to produce a `<mmultiscripts>` tag telling wxMaxima which pre- and post-super- and/or subscripts are requested I would be happy to modify the current C++ code to understand this notation.

**Comment by robert-dodier** [comment]
@gunterkoenigsmann well, my advice is to process either only MathML tags or the modified wxMathML tags. Trying to handle both seems like it could easily lead to confusion. If you have to pick one or the other, my advice is to process only MathML tags. Just my $0.02.

About `mmultiscripts`, I will work on how to generate those tags. I think it won't be difficult. 

@richardgobeli I think the tensor display you mention could be handled by introducing placeholder spaces. I believe we would need to have an additional declaration to know that it's needed. Let's get through the basic display stuff and then circle back to that.

**Comment by robert-dodier** [comment]
I've open #1195 to track the progress on the implementation of the display of pre/post sub/superscripts in wxMaxima. Since that is a new feature and it's being tracked by #1195, I'll close this issue. Further discussion should be directed to #1195.
