### ISSUE TITLE
Refusing to send cell to maxima: Mismatched parenthesis Maxima problem

### ISSUE THREAD

**Issue by Lancer-Lab** [wxMaxima-developers/wxmaxima#1197]
I'm using the latest version of maxima which is wxmaxima 5.43.0 win 64. But, when I type in 'diff code is totally fine. Then, I continue to type ic2 code, it gave me that message? How do you solve this? if patch needed, how do you patch maxima?

**Comment by gunterkoenigsmann** [comment]
Wow... ...which was the exact command that caused the Problem?

**Comment by Lancer-Lab** [comment]
ic2 command

**Comment by gunterkoenigsmann** [comment]
The problem is that in the command you tried to send to maxima a parenthesis is opened, but not closed. Or closed, but not opened. Or that a round parenthesis is opened and a square one closed or similar.

...or that wxMaxima believes any of these to be the case ⇒ in order to find the problem I'll need the full offending command including all parenthesis.

**Comment by KubaO** [comment]
@Lancer-Lab  Please provide exact steps to reproduce, otherwise I'll have to close as I don't know how to reproduce it.
