### ISSUE TITLE
characters with tilde

### ISSUE THREAD

**Issue by danielvolinski** [wxMaxima-developers/wxmaxima#1203]
Hi All,
Is there any way to put a regular character with a tilde (~) on top of it?
Is there any way to put a regular character with an accent (^) on top of it?
Thanks,
Daniel

**Comment by gunterkoenigsmann** [comment]
You mean a character that normally comes only without a tilde or an accent? Or do you mean one that can come with an accent, for example in spanish text?

**Comment by danielvolinski** [comment]
Yes, a character that normally comes only without a tilde, like a simple r and I want to define a variable that is r with a tilde ~ or an a accent ^ on top of it. Is this possible?
Daniel

**Comment by gunterkoenigsmann** [comment]
There is a chance that if you add the symbol from https://www.fileformat.info/info/unicode/char/0303/browsertest.htm to the "mathematical symbols" sidebar you can combine such letters. On my own computer that seems not to be a possibility wxWidgets supports, though.

**Comment by gunterkoenigsmann** [comment]
If you escape the combining tilde character with a backslash it actually seems to work, but only if it is inside a variable name: c\̃d

Will have a look at why there is this restriction.

**Comment by gunterkoenigsmann** [comment]
Seems you need first the character you want to equip with a tilde, then a backslash, and then the combining accent or tilde:
    
      d\̃

Your mileage might vary, though, with different fonts, see http://unicode.org/faq/char_combmark.html. Part of the complexity of creating a font with complete support for combining diacritics is described at https://xkcd.com/1813/.

**Comment by danielvolinski** [comment]
I get the following:
ldisplay(d\~:5)$ => d~=5
ldisplay(c\~d:5)$ => c~d=5
Daniel

**Comment by gunterkoenigsmann** [comment]
That looks like you were using a normal, not a combining tilde.

Tomorrow's version of wxMaxima will come with a "Help/Variable names" tutorial you might (if your OS allows this) be able to drag-and-drop combining diacritics from.

**Comment by richardgobeli** [comment]
You are make great progress!
![image](https://user-images.githubusercontent.com/31253976/73129875-f11a9080-3fb2-11ea-8ff1-023bf33bed84.png)

How do you enter a unicode character on the wxmaxima screen?  I can't seem to get the correct combining tilde or accent after the backslash to make this work.  
In windows word I can enter a unicode character by typing 0303,alt-X and then it puts the tilde on the previous character.  But this does not work in wxmaxima.

I did get it to work by copying the character you entered in the example.   It was hard to copy, because it is a invisible character and is displayed on the previous character on the input line.
![image](https://user-images.githubusercontent.com/31253976/73129934-65a1ff00-3fb4-11ea-9ca9-6de3bdc2b09b.png)

I did get it to work also by putting it on the math symbols screen, but these character are not saved in the configuration.  Only character saved are the three you have as default added symbols.
![image](https://user-images.githubusercontent.com/31253976/73129953-c7626900-3fb4-11ea-88b4-8c2a7ef863e7.png)

![image](https://user-images.githubusercontent.com/31253976/73129955-f973cb00-3fb4-11ea-8e94-97432cd55765.png)

They do display as separate characters on the symbol table.
![image](https://user-images.githubusercontent.com/31253976/73129964-3475fe80-3fb5-11ea-9cc9-0eeb4324806a.png)

The menu has a type mistake in front of tutorials on the web.
![image](https://user-images.githubusercontent.com/31253976/73129981-920a4b00-3fb5-11ea-98a1-a27dbd1d1db8.png)

**Comment by richardgobeli** [comment]
I found a little program that will pop up a window to install a U+ code at any time using windows.
It is a program running in background and is called with ALT keypad plus.
It is called unicodeinput.

![image](https://user-images.githubusercontent.com/31253976/73211771-7f595880-4112-11ea-97b4-71d40cdbc7d2.png)
I tested it and it works in WxMaxima.

**Comment by gunterkoenigsmann** [comment]
In tomorrow's nightly build adding characters to the symbols pane should work, too.

About the Alt+x: Should it expect numbers in decimal or in hexadecimal format?

**Comment by richardgobeli** [comment]
They are unicodes so then hex digits. 
The tilde ̃ is 0303,ALT-x. 
The circumflex accent ̂ is 0302,ALT-x
You can google windows word AlT-x to see more about it.

**Comment by richardgobeli** [comment]
Word has this symbol screen showing all of the combining diacritics starting at 0300 to 036f.
Here is the start.
![image](https://user-images.githubusercontent.com/31253976/73330856-a2c1f780-4227-11ea-9bab-c71e7c7e46a6.png)
Here is the end.
![image](https://user-images.githubusercontent.com/31253976/73330885-b66d5e00-4227-11ea-8346-f9adf864a305.png)

**Comment by gunterkoenigsmann** [comment]
The official description of the unicode consortium on which characters exists seems to be gpl-compatible, but >1,2 Megabytes long. Adding a panel that uses them would increase the size of the wxMaxima binary by about a third. On the other hand such a panel could be useful... ...unsure if I should write one...

**Comment by richardgobeli** [comment]
The alt-x does move back across the 4 digits, but they are not deleted and the unicode character is not inserted.
![image](https://user-images.githubusercontent.com/31253976/73544753-7d87e180-43ff-11ea-90f1-1022a115ab83.png)
I was not thinking of you adding the extra character screens, but only showing the possibility of how many of these characters exist.

**Comment by gunterkoenigsmann** [comment]
In tomorrow's build I had another go at alt-x: Seems I used an undocumented feature that happened to work on Linux - and I tried to implement a full-fledget unicode sidebar not knowing how big unicode has become. So I disable the sidebar on every start-up before it uses up too much time...
