### ISSUE TITLE
The temporary files are not delete.

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1219]
When I close wxMaxima, the temporary files are not delete.

![Error_1](https://user-images.githubusercontent.com/59099908/75788794-0086b980-5d69-11ea-9ca7-f83136f64143.jpg)

![Error_2](https://user-images.githubusercontent.com/59099908/75788798-0381aa00-5d69-11ea-8fc8-36d425ee32f7.jpg)

**Comment by gunterkoenigsmann** [comment]
You are already the second user that reports this which hints that this is a common problem. Normally my guess is that such things are caused by a combination of a operating system that doesn't allow to mark files that are still be read for deletion and a virus scanner that prevents to move and to delete the file because it still wants to scan it.

**Comment by ReneSci** [comment]
Yes  - this issue also prevents the user to just press "save". You have to rename the worksheet each time you want to save the worksheet.
