### ISSUE TITLE
URL to help files

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1221]
The URL's are not correct.

![Path_1](https://user-images.githubusercontent.com/59099908/76122557-984d0780-5ff6-11ea-80cd-a0cf31c08672.jpg)

![Path_2](https://user-images.githubusercontent.com/59099908/76122569-9f741580-5ff6-11ea-8d0a-d06612ae642b.jpg)

**Comment by gunterkoenigsmann** [comment]
I still don't understand what was going on there. But with a bit of luck in today's nightly build the help system works again.

**Comment by ljselmaier** [comment]
Only help system 'wxmaxima' works again.

A now error:

![Error_4](https://user-images.githubusercontent.com/59099908/76167398-a6ba3100-6166-11ea-838a-e43d30d1406b.jpg)

**Comment by gunterkoenigsmann** [comment]
Arrgh! Do you happen to know how to trigger this error?

**Comment by ljselmaier** [comment]
Now then browser starts. But the URL ( help system 'maxima' ) are not correct.

![MaximaHelp_03](https://user-images.githubusercontent.com/59099908/76348554-ac4f7c80-6308-11ea-8fa8-732ba2ad4aea.jpg)

**Comment by daute** [comment]
Thank you. The "c.com" gave me the idea, that the file URI was wrong (as the path on Windows starts with "C:...").
The strange thing: Now it should be correct, but the Maxima manual is not found - and I have no clue why. It works, if I type in the URI in the error message char by char. 
And the **wxMaxima** manual is found and displayed (Does that work for you too?).

**Comment by ljselmaier** [comment]
wxMaxima manual is found and displayed.
Maxima Manual is not found. This error appear:

![Maxima_01](https://user-images.githubusercontent.com/59099908/76410575-6d650980-6390-11ea-992e-3ab94e3acb5b.jpg)

**Comment by ljselmaier** [comment]
Now, it is okay.
Thanks.

**Comment by gunterkoenigsmann** [comment]
That is good news! Wolfgang has found a much more elegant way of opening the browser that makes much more elegant code.

What I am unsure about: Compiling the list of maxima commands there is help for requires loads of time. Should I compile this list in a background task once Maxima has started (which means that the CPU fan will whirr up on every start of wxMaxima and startup will be a bit slower if the number of available CPUs is below 5 or similar)... ...or is it OK to compile this list only the first time it is needed? I tend to the 2nd option. Alternatively I could perhaps find a way to compile the list 30 seconds after startup or when it is needed, whatever comes first....

**Comment by gunterkoenigsmann** [comment]
I have now implemented a method that compiles the help anchor list in the background after waiting for everything important to be initialized. Seems like this feels fast even if it objectively isn't completely.

**Comment by ljselmaier** [comment]
This is okay, but the button 'F1' is not working.

**Comment by richardgobeli** [comment]
All helps for F1, WxMaxima, and Maxima all go to the web browser.
I find the WxMaxima window is easier to navigate for using the help.
Is this now the default?  I am using Windows 10.
![image](https://user-images.githubusercontent.com/31253976/76688438-c3d58080-65fa-11ea-96a4-52a9bfba37ca.png)

**Comment by gunterkoenigsmann** [comment]
Any help is welcome - and when I thought about giving you write access Wolfgang asked me why I didn't grant you write access...

The advantages of the new default are:

- The web browser doesn't crash every few minutes on half of the platforms
- it is able to display the whole manual at once without getting extremely slow which allows searching the manual with the user's browsers best search function (most browsers have incremental search, for example).
- It is able to display animations and SVG files
- It isn't dependent on the .hhp file that nowadays that there is no other tool any more that requires this file has gotten kind of hard to provide any more.
- The web browser doesn't just feel ancient

The drawbacks of using the web browser instead of the built-in help browser are:

- It doesn't open up in a fraction of a second and
- it doesn't contain the nice navigator sidebar.

Both options have advantages. But I hope the web browser will make more users happy than the integrated one. Sometimes all one can do is searching for the lesser of two evils.

**Comment by richardgobeli** [comment]
OK, That makes sense.  I was looking so hard for the search option, that I did not think of using the browser search.  LOL.

**Comment by gunterkoenigsmann** [comment]
One [hopefully useful] additional feature we have gained this way is the ability make the right-click menu show suggestions for commands from the manual that are similar to the word under the cursor. If you want to test it: This feature is included in today's nightly build. But only is available about 15...20 seconds after start-up.because I didn't want to delay the start-up process for it.

**Comment by daute** [comment]
Using the browser search function usually provides further goodies, which was not available with the included help browser, e.g. on can search case-sensitive (or not), search for complete words, ... using Firefox (and probably other browsers too).
And one see more than one help topic at a time (in multiple browser tabs/windows), e.g.: is `wxdraw2d()` or `wxplot2d()` better suited for my task?
