### ISSUE TITLE
change locations in config file for 'fontSize' and 'mathFontSize' parameters

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1230]
I suggest a minor (internals) enhancement: moving 'fontSize' and 'mathFontsize' config file options to their respective 'Style' sections, that is, 'Style/Default' and 'Style/Math'. 

As they are, they serve no useful purpose sitting in the config file's main body.  Also, the 'Style/Default' gets its 'fontsize' set to the default (and unused now) value of 12.

PS Thanks for the prompt closing of #1229! 
(and how does one put those coloured 'label:' ribbons in the subject line?)

**Comment by zmth** [comment]
seems changing most anything in in the styles and config and saving them in it's default file style.ini at least in windows setup does not take effect after one closes maxima and brings it up next time whether or not it is the same .wxmx file or not.

**Comment by Kaiser1401** [comment]
seems related to #1103 (config is written but not read)

**Comment by KubaO** [comment]
`fontsize` and `mathfontsize` already are in the relevant Style sections, since `Style::Write` doesn't discriminate and writes those anyway. But they are unnecessarily written to the main body. And these two settings are a mirror of the sad state of the font configuration code - they have matching `m_fontsize` and `m_mathfontsize` members in the `Configuration` class, and there's code all over the place that "merges" those values with the ones in the styles All that is superfluous.

I'm working on finishing up the transition to the font cache, since that brings a major performance improvement and is necessary to enable the configuration fixes. The "out of style" settings will be taken care of next. This will take maybe a week, as all this is late night work.
