### ISSUE TITLE
font face in text cells is the same as the default one after the commit in #1229

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1232]
Just noticed this. The font face config option for 'Style/Text' is shown and may be changed in the styles dialog, the setting is retained in the config file, but it isn't actually used -- the default face from 'Style/Default' is used instead.

Sorry for generating more trivial work for you, but I don't understand the code myself.

**Comment by yurytch** [comment]
Looks like the Default, Math and Text styles work finally as expected, indeed.
The 'Heading' set of styles also seems to work okay.
Many thanks!
I'm only wondering about that renaming of 'Text cell' to 'Status text' (in the config dialog).
Why couldn't it stay 'Text cell'? As an explanation, something like 'Comment' would do (I use it both for comments and for descriptions). But definitely not 'Status text'. Better yet, revert this string to the familiar 'Text cell'.

**Comment by gunterkoenigsmann** [comment]
I had a hard time what the cell names meant, SOE I tried to rename the styles I had problems with. But AFAIK you have write access => feel free to revert or to improve any of my changes.

**Comment by yurytch** [comment]
What, **_I_** have write access? Thank you, but your trust in me's misguided )) -- I'm, like, the last person on the planet who doesn't understand git. I can 'download the sources' and  'select a specific branch' for that purpose, but that's that.
The hard time with meanings of cells styles' is likely caused by some styles just not being used by the code anymore. 
The meaning of 'Style/Text' is quite clear, though -- it's a style for (unparsed) cells in which any text may go. I use those a lot to 'comment the code', both for my own use and for presentation purposes. (There's a 'Text cell background color' setting there, too.)
So, please would you put back 'Text cell' in 'Style/Text' description in the config dialog (instead of 'Status text'?
Maybe 'Text cell (descriptions, comments, etc.)', if the previous string wasn't informative enough.

**Comment by gunterkoenigsmann** [comment]
Don't be afraid: Everybody starts at https://xkcd.com/1597/ - or uses the "Pencil" symbol in the file view at https://github.com/wxMaxima-developers/wxmaxima/tree/master/src.

If anything goes wrong: Don't be afraid, I'll fix it. Often things that started as a small step in the Right Direction end up as important features.

**Comment by Kaiser1401** [comment]
might be related to #1103 (e.g. config is written but never used)

**Comment by KubaO** [comment]
Re the xkcd comic: that was pre-SmartGit. If you're not using it, you're doing it wrong™. I'm serious :) (No connection with developers, just a happy user of an extremely important productivity tool). It's not some "light" shell over git. It's the interface that turns git into the power tool it truly is, without having to load your mind full of commandline incantations. Said incantations and chants are important in scripted activities like builds or repo maintenance, but for day-to-day development work, they are just a burden.

**Comment by yurytch** [comment]
Incantations are okay, I actually prefer commandline for many tasks, but certain, like, perspectives in git's workflow completely stop me. 

E.g. I don't get how the branches are (finally) merged, especially if there are conflicting edits.

Maybe there's a free (e)book or something. Every materiel I've seen up to now wants to teach me on trivial or unrelated matters.
(Have (re-)searched right now on "git workflow"; Atlassian's looks the closest, maybe I'll have a go with that one.)

**Comment by KubaO** [comment]
You have to do conflict resolution, and doing it the usual way by manually editing diffs in vi is less than optimal, let’s just say. It really needs an interactive graphical tool, and additional tools to investigate the history of the code you’ve merging. SmartGit has impressive blame and investigate tools that deal well with moved blocks of code, vanishing files, and other facts of life.

There are three approaches to merging:

1. Rebasing the branch to be merged on top of the target branch. It “replays” all the commits, and any time overlapping lines have been edited both in the rebased branch and the rebase target, you have to resolve conflicts before it can proceed.

2. Creating a fresh branch, cherry picking all commits from the to-be-mergeds branch, as that often yields less conflicts (at the price of some risk of collisions that were important being undetected), and then merging the fresh branch without conflicts.

3. Inverse of 1 or 2: branch the master at the point the feature branch was based, merge the feature into that historic master, then merge the newest master into that, and finally merge the “parallel master” onto the new master. In rare cases this yields better results, but I have not had to resort to that in a long time.

The most important way to with conflicts is to deal with small changes. If you’re doing a big refactor, then the branch you do the work in has to be planned to be abandoned, and instead you need to split it into small changes (potentially cherry pick them), and merge these from small feature branches.

That’s the approach I take: all major work is treated as an experiment/prototype. Then I let it “rest” for a few days or weeks. Then I look at it again, and create lots of smaller feature branches that I merge individually. I often end up with better code that way, since this is akin to an internal review.

If you look at the “big” feature branches I created, there’s a lot of changes there, many of them speculative.

**Comment by yurytch** [comment]
Thank you, @KubaO, that was very impressive and quite a volume of text to type. Also, a bit above my head, regretfully. 
I seem to get an idea that there IS a lot of 'manual' (non-automated), one-by-one selection work, but such texts are, as yet, too advanced materiel for me. I hope to get back to it one day, though! ))

**Comment by gunterkoenigsmann** [comment]
One of the coolest things about git is that a real ecosystem has formed around it: github, many guis - and that everyone can find a tool that is most fit to the current needs.

I personally do most things I can from the console. But I have set the mergetool and diff viewer to "meld" so if there is a complicated thing to do "git mergetool" and the application "meld" will provide me with a powerful gui tool. One of my former bosses often directly manipulates files in the .git directory and always wants me to do things as low-level as he does. Some devs use the git client integrated into their text editor - and there are powerful GUIs that allow you to do everything without ever having to learn the console commands. All of these methods have their advantages.

**Comment by KubaO** [comment]
I still urge everyone to try SmartGit :) It’s cross platform (Linux, win, MacOS) and free for non-commercial use. I don’t know if any other tool is even remotely close to it. At least a couple of years ago it was so far ahead of everything else that it wasn’t even funny. Their blame/investigate tool alone is a game changer when tracking what happened to the code (who changed it, when, how it moved around in case of copy/pasted, etc).

Given how much use you’ll get out of a good git front-end, messing about with half-baked tools just kills productivity.

**Comment by KubaO** [comment]
I believe that this problem is fixed now. Please test and reopen if still present. Gunter: could you please check on your system that the style configuration works correctly? There are no more bugs I know of that affect it on X11.

**Comment by gunterkoenigsmann** [comment]
Styling never used to work. But it seems to work now.

**Comment by yurytch** [comment]
There are some minor glitches in 20.06.6 on linux, but hardly worth spending time on right now. 
It is possible now to set all three main fontfaces and sizes, and keep them set. 
Let's consider the issue fixed?

**Comment by KubaO** [comment]
I’m very happy to hear that :)

**Comment by KubaO** [comment]
Fixed through various ongoing commits :)
