### ISSUE TITLE
Ambiguous rendering of nested squareroots

### ISSUE THREAD

**Issue by TomasRiker** [wxMaxima-developers/wxmaxima#1306]
wxMaxima displays squareroots in such a way that different expressions can look exactly the same. Nested squareroots don't have a margin on their top side so that the horizontal lines merge. See this screenshot:

![image](https://user-images.githubusercontent.com/295205/84749129-dbd1ed00-afb9-11ea-95e6-23a00bb9874d.png)

This is how it should look:

![image](https://user-images.githubusercontent.com/295205/84749248-002dc980-afba-11ea-83a7-f77f747a3749.png)

Or even like this:

![image](https://user-images.githubusercontent.com/295205/84749275-0ae85e80-afba-11ea-918a-85e6c9229f73.png)

**Comment by ajmirelesme** [comment]
I was going to report the same bug. (See image)
![Report Display](https://user-images.githubusercontent.com/67128248/85080853-80555a00-b187-11ea-9629-7600ca7ef599.JPG)

-------------------------------------------------------------
wxMaxima version: 20.06.6_MSW_OpenMP201511+Locks
using wxWidgets version: wxWidgets 3.1.3
Maxima version: 5.44.0
Maxima build date: 2020-06-08 22:46:53
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:/Users/Joel Mireles/maxima/
Help dir: C:\maxima-5.44.0\share/doc/wxmaxima
-------------------------------------------------------------

**Comment by KubaO** [comment]
I hope that it wasn’t me who broke it. I was messing with that code at some point but am now unsure if anything ended up committed. But I’m on my phone only at the moment so I won’t be messing with the blame tool :)

**Comment by ajmirelesme** [comment]
Thank you @gunterkoenigsmann !
@KubaO haha well if you think it might have been because of you and feel guilty, may be you could make a little improvement to the nested square roots by adding the little tip at the end of each square root just as Tomas showed in one of the images above.

How do I implement this fix into my computer? Do I have to download the file provided in fff6537 and substitute it for the former one?

Quick question, have superindexes been added before roots in Maxima? To refer to, say, the fifth root of such?    ⁵√x

Anyway, keep up the good work!

**Comment by ajmirelesme** [comment]
@gunterkoenigsmann thanks for adding the serif to the sqrt's, but how do I make these changes in my PC? Since I have not made any installations/updates of any sort I still see ambiguous square roots and no serif. Last thing I did was download the latest release. From where I am standing, without my questions answered, I would have to wait until the next release to see any changes. I did what I could and tried to understand how to compile from source (which I do not really understand what it means). Excuse my ignorance. I would understand if answering my questions would be time consuming and not worth trying.

**Comment by gunterkoenigsmann** [comment]
Normally the answer would be the installer from https://wolfgang.dautermann.at/maxima/nightlybuild/. But it seems like currently it cannot be built.
Am still waiting for spare parts for my PC. But I will ask Kuba to look into it.
