### ISSUE TITLE
Question answering mechanism is somewhere between non obvious and broken

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1312]
wxMaxima has a mechanism to remember and answer questions if e.g. a parameter is an integer. Usually I can avoid these with declare and assume, but now I have a case where it asks if some term is integer, and this cannot be declared or assumed afaik (the term asked about does not occur in the input, so I cannot even substitute it).

Now the issue is that every time it runs over the script it asks again and remembers a new answer if I give one. I end up with 20 'n' in the script and when running the script it seems to produce 20x the n input (I get 20x an output with contents n. Deleting all output doesn't remove the n.

Also when hovering over the answer there is a hint which says there is an "automatically answer questions" button. Where is it?

I have checked the "Offer known answers" checkmark in the settings. I found that using shift+enter to answer avoids adding a new answer but still it keeps all the old answers and there is no obvious way to get rid of them.

**Comment by gunterkoenigsmann** [comment]
Wow... ...that looks like wxMaxima on receiving questions forgets to add an EditorCell that allows to input an answer.

Test case:


       askinteger(I);


Maxima asks but to the question no editor is attached that allows to enter an answer.

**Comment by KubaO** [comment]
I have a suspicion I broke it but let me check.

**Comment by gunterkoenigsmann** [comment]
My guess is that it was always broken and you partially unbroke it.
Now I don't know what to do: I like to write code in a way that if something is broken it breaks in a way obvious enough we see it or at least get a bug report.

The problem was this time that we acually appended an EditorCell to the question. But that cell always believes that it still needs to be recalculateed, which means it was never assigned a position to. I believe this cell needing to be recalculated is a bug. But if I tell the cell to accept the position from the Draw() command even if it is in the "needs recalculation" state everything works....

**Comment by gunterkoenigsmann** [comment]
(Changed my last comment to make it clear that my commit was the one who broke it)

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : thanks - more reasons to make a new Mac build ;-)

One question: is there actually a way to automatically answer questions as advertised in the hint? I think a good solution would be to use a pre supplied answer if one evaluates with Ctrl+R or Ctrl+P or selecting multiple cells and pressing shift+enter, but asking if a single cell is evaluated - so that one can override the answer.
