### ISSUE TITLE
An Assertion Failed! /builddir/build/BUILD/wxmaxima-Version-20.06.1/src/CellPtr.h(179): assert "(!obj && m_cb == &ControlBlock::empty) || (obj && m_cb == static_cast<const Observed*>(obj)->m_cb)" failed in base_reset().

### ISSUE THREAD

**Issue by pvetter** [wxMaxima-developers/wxmaxima#1351]
ASSERT INFO:
/builddir/build/BUILD/wxmaxima-Version-20.06.1/src/CellPtr.h(179): assert "(!obj && m_cb == &ControlBlock::empty) || (obj && m_cb == static_cast<const Observed*>(obj)->m_cb)" failed in base_reset().

BACKTRACE:
[1] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[2] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[3] wxEvtHandler::TryHereOnly(wxEvent&)
[4] wxEvtHandler::DoTryChain(wxEvent&)
[5] wxEvtHandler::ProcessEvent(wxEvent&)
[6] wxEvtHandler::ProcessPendingEvents()
[7] wxAppConsoleBase::ProcessPendingEvents()
[8] wxApp::DoIdle()
[9] g_main_context_dispatch
[10] g_main_loop_run
[11] gtk_main
[12] wxGUIEventLoop::DoRun()
[13] wxEventLoopBase::Run()
[14] wxAppConsoleBase::MainLoop()
[15] GOMP_parallel
[16] __libc_start_main

Fedora 32 
Name         : wxMaxima
Version      : 20.06.1
Release      : 1.fc32
Architecture : x86_64
Size         : 12 M

Had opened up "10 minute (wx)Maxima tutorial"
issued commands on top of file:
apropos("log");

float(log(2));
float(log(10));

and then tried to execute the last block of two commands. wxMaxima remains hung with the circle cursor spinning. Does not appear to be consuming much CPU.

**Comment by pvetter** [comment]
also, unable to click on menu options with the spinning circle cursor. Is there any way to interrupt wxmaxima in this state besides killing the process?

**Comment by gunterkoenigsmann** [comment]
Will look into this issue today.

The question the dialogue telling "An Assertion failed!" asks is often formulated in a way that it is hard to find out what it means. What this dialogue says is:

 1.) The program has found a bug that needs to be reported to the developer. This you have done and you also have included all the information I believe to need in order to fix the problem.
 2.) It asks if you want the dialogue to make the program continue - or if you prefer to make the dialogue issue an invalid command in order to manually crash the program: If you happen to be a developer that has a debugger being able to crashi the program in the place it has detected a bug is in is a practical feature: In this case the debugger jumps to exactly the place the bug is at - and the stack contains all the information that is needed in order to find out how you got there. => Just tell the dialogue that you want to continue - and that you don't want to see this dialogue again and everything should work fine.

As a 2nd thought we probably should add the 10-minute tutorial as a test case for the automatic tests.

**Comment by KubaO** [comment]
Well, let’s look at the version string: that one did have that problem. So this can be closed - the identical issue was filed right after 06.1 got released and then I fixed it. There’s has been no such assert in CellPtr.h at line 179 for a month or more.

**Comment by pvetter** [comment]
Thank you for looking into it. I do not remember an option to continue, but I may have overlooked it.  Can you recommend a recent release that was particularly stable?

**Comment by KubaO** [comment]
Nightly :)

**Comment by KubaO** [comment]
...or a later 20.06 release - there were several.

**Comment by gunterkoenigsmann** [comment]
The only place where copying involves writing (and later reading) image files should be things like copying svg versions of the plot to the clipboard using wxWidgets versions that refuse to read these graphics from memory. And doing so in theory can only fail if the system's temp folder isn't writable. I guess on windows if you type in %temp% as the location in the windows explorer you will be brought to the directory in question.
...and today's nightly build from http://dautermann.at ist excellent. I cannot guarantee for tomorrow's build, though, as I did a big change in order to save RAM. But if that introduced any subtle error they most probably will be resolved again the day after tomorrow.

**Comment by KubaO** [comment]
I'm closing this since the assertion bug has long been fixed. @pvetter: please file a new issue if you have problems with a 20.07 release or the nightly.
