### ISSUE TITLE
Text cell does not get extended when adding lines

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1352]
When inserting a text cell with Ctrl+1, the cell does not get extended when lines are added, e.g. with enter. So after a few lines the text overlaps with the following cell.

Version: master of today (8848017d6c163147dc9ada77fb8e69b6746957c0)

**Comment by MSoegtropIMC** [comment]
P.S.: the same also applies to formula cells.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : thanks for fixing! Please let me know when there is a good time to test again. The search and replace issue (#1353) is also pretty bad since it might really badly corrupt a development. Otherwise I am not aware of really serious issues.

The menu issue might be fixable. A member of the wxWidgets team looked into wxMaxima and suggested to review our installation packages. Some issues in there might be the root cause (rather than the code).

**Comment by gunterkoenigsmann** [comment]
The other two issues look completely weird. But I honestly have no idea where they might come from: On my own computer they aren't reproducible. Am currently trying to switch the nightly build to the next wxWidgets version so if it is an wxWidgets install problem they might be resolved in a jiffy. I cannot guarantee, though, if we won't see new issues with he new version, instead...

**Comment by gunterkoenigsmann** [comment]
I just remembered: The menu issue was MacOs-only. On MacOs I don't have any influence what is installed ;-(

**Comment by doswellf** [comment]
The ubuntu 20.04 wxmaxima had a crash-on-complex-unicode bug. I compiled wxmaxima from a github clone last week, which fixed the crashing when loading a .wxmx file. The only issue is that enter does not add a new line to a text cell. The text cell won't try to overlap any cell below it, but I can only enter one line into a text cell. 
The system is using ubuntu's packaged wxwidgets. I can use another ppa if available, or just build wxwidgets from a git clone as well, then rebuild wxmaxima using that wxwidgets installation.  But if it's just due to a cmake or configure switch, please let me know.

**Comment by gunterkoenigsmann** [comment]
On my computer pressing enter does add a new line [I am using Ubuntu, too].

My guess would be that there might be a difference between the keypad enter and the normal enter key. Or that the "enter causes a newline" config dialogue setting is causing your problem, perhaps...

**Comment by doswellf** [comment]
Thanks, will check my settings and test both enter keys.
