### ISSUE TITLE
Files with wrong name appear to be empty

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1363]
A bad bug. But no idea what causes it:

- Name a file `binm19 - Copy (2).wxmx`
- Fill it with all the maths you want
- save it
- and try to open it.

wxMaxima will try to open it and seems to believe it succeeded. But it cannot find any contents. Renaming the file to a different name resolves the issue. But who on earth would think of that solution?

**Comment by KubaO** [comment]
Does not reproduce on Windows in a MSVC build.

**Comment by KubaO** [comment]
I can't reproduce it using master under Ubuntu Focal in a VM, built using g++ 9 (default for the distro). The build approximates what's done on travis, i.e. uses fully updated focal with cmake from kitware.

I'll more detailed reproduction instructions, since I just can't see the problem on either Windows nor Ubuntu Focal.

**Comment by KubaO** [comment]
Could it be that this bug was present a month ago, but not now?

**Comment by KubaO** [comment]
Gunter, does this still reproduce for you? If it does, could you point out the exact Debian version you're using, and the compiler you're using for it (g++ vs clang, what version).

**Comment by gunterkoenigsmann** [comment]
Seems like it works for me now.
