### ISSUE TITLE
Debug messages constantly scrolls up and down 

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1364]
If I type a letter into the worksheet the debug messages sidebar scrolls to the first message - and if a message is output it scrolls to the last. But why? Clearly that isn't good for performance...

**Comment by KubaO** [comment]
1. Have a debug build of wxWidgets, so that the sources are available for stepping into - you need it anyway, I can’t imagine working on wxMaxima without it.

2. Run the program under the debugger.

3. At some point, pause it, copy-paste the address of that widget into an open scratch pad/text editor, then zero out the widget address in the structure that holds it.

4. When wxMaxima (not wxWidgets itself - the widget still exists, and the addresss of it is held in event tables and such, etc) tries to manipulate the widget, you get an access violation and can see what’s on the call stack.

  If this happens in a wrong spot, you can add a little debug code that does something like

if (m_historySaved)
  m_history = m_historySaved;
// use history
if (m_historySaved)
  m_history = nullptr(

  And of course after history is constructed we’d have:

if (true) { // debug code
  m_historySaved = m_history;
  m_history = nullptr;
}

I imagine that someone may inadvertently given the widget focus while using the program, and perhaps the worksheet will still gets the letters, but the history will react to them as well.

In general all these problems happen because the code is so convoluted that it’s hard to change it without introducing bugs. My very long term plan is to reduce the code size by 50% or more, and have it understandable by people without deep insight into the project. As it stands, it’s of course a mess, but it has lots of potential :)

**Comment by gunterkoenigsmann** [comment]
The "debug messages" panel logic on the wxMaxima side isn't too complicated: wxMaxima creates a wxTextCtrl and then tell wxLog to log the messages there. No further calls to it are made on the wxMaxima side. Still it constantly scrolls to the beginning and the end.

---

The "zero everything" approach is creative. But it will cause the debugger to be invoked on every access to anything "debug sidebar"ish. What I will try to find out first when I have time to debug this is to find which are the scroll routines I have to add breakpoints to.

**Comment by gunterkoenigsmann** [comment]
I believe I found it: The debugging messages sidebar seems to be cleared by wxWidgets on each new debug message and to be filled again message by message. Might that be possible?

**Comment by KubaO** [comment]
It’s probably the wrong type of widget maybe? Otherwise, there should be an option to keep it in place. Maybe some common logic from History could be factored out and reused in both? Eg. perhaps the search could be a universal feature.

**Comment by gunterkoenigsmann** [comment]
I don't know if I could have done anything wrong: I created a wxTextCtrl and used a wxStreamToTextRedirector to send all messages there. Feels very fool-proof. But it looks like if I do a wxLogMessage() that on GTK3 seems to volve the wxTextCtrl to be drawn multiple times if the log buffer is long. Will debug this a bit more and if my analysis so far is right that looks like being a candidate for a bug report to wxWidgets.
