### ISSUE TITLE
Command "Select all"

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1389]
![wxMaxima_1](https://user-images.githubusercontent.com/59099908/91668070-bdd04f00-eb09-11ea-9c09-270e83defa34.jpg)

**If you select all cells with the "Select all" command, the relevant cells are not activated.**

**Comment by KubaO** [comment]
So, you’re saying that pressing Ctrl-A doesn’t select cells? Interesting. I need to see if it reproduces.

**Comment by KubaO** [comment]
Works for me. Select All has always required up to two activations: if the caret is in the cell, it will first select all the contents of the cell. Then, upon subsequent activation, it will select all of the cells in the document. Perhaps you're seeing this behavior and not realizing that's the case. Otherwise, I'll need to have a document to reproduce this on, because in my case, it works just fine with `all-celltypes.wxmx` as well as other documents I have.

**Comment by gunterkoenigsmann** [comment]
For me it works, too. 

Normally I would now ask if the problem is language specific? But in this case I would guess wxMaxima is set to "German" or "English"... ... perhaps we are missing a detail on what to look at or on how to reproduce...

**Comment by ljselmaier** [comment]
**I meant:**
If you use the 'Select all' command as the first 'Select' command after starting the program, commands such as 'Copy', 'Cut' are not enabled.

**Comment by KubaO** [comment]
Ah yes, this has been an ongoing issue for a few weeks now. IIRC Gunter made some menu changes that affected that?
