### ISSUE TITLE
Selection cannot be extended from the output of one cell to another

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1396]
How to reproduce:

- Create two code cells with output
- Left-click into the output of one code cell and move the cursor to the other.

What I believed would happen:

- Both GroupCells are selected entirely

What happens:

- The selection ends in the output of the cell it started in.

**Comment by KubaO** [comment]
Interesting. I might have a fix for that.

**Comment by gunterkoenigsmann** [comment]
That would be good news: This is the only bug I want to fix before the new release - and I think the fixes we made until now prompt for one.

**Comment by KubaO** [comment]
Note: this is not a recent regression. The behavior is present in 20.04.0 and 19.05.7.

**Comment by KubaO** [comment]
About the release: there are more regressions related to recalculating cell sizes that I've noticed, and it may well be that I have to integrate my large-scale changes to permanently fix that. So, release-wise, if you wish to release I'd say go for it. I won't be able to backport this particular bug fix since it will take too long. It will land with the larger changes.

**Comment by gunterkoenigsmann** [comment]
Sounds like a good decision => Will make the release tomorrow.
