### ISSUE TITLE
Possible threat ?

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1410]
I have just realized that since 28 August 2020, each time I run wxMaxima a note is created in the Windows 10 "Protection History"
![image](https://user-images.githubusercontent.com/2638713/95323618-c3eee380-089e-11eb-8931-ac0db2a86126.png)

Do you have any idea what this is?

**Comment by KubaO** [comment]
It’s Windows being snarky and blocking Microsoft’s own product. Or you got malware. One file named CcmExec.exe is a part of the operating system. 

Since a file by that same name (it doesn’t mean it the same file!!) got qualified as non-prevalent and/or new/fresh file, it’s definitely not signed by Microsoft and it’d be used by malware to disguise itself. Again - this is not the same as what comes bundled with Windows, even though it may have the same name.

So I’d say that you have a problem that may be benign (Windows being stupid) or not (Windows blocking genuine malware), but it has nothing to do with wxMaxima; wxMaxima is just the trigger.

**Comment by gunterkoenigsmann** [comment]
wxMaxima doesn't start ccmexec.exe directly: It starts maxima.bat, it starts gnuplot and maybe uses the default internet browser as an help browser. 

All I was able to find about ccmexec is that it is somehow used for desktop configuration management. I guess you can use that service to render this specific application with specific compatibility mode - or for moving Data from one computer to the other. And google tells that McAfee doesn't like that program. Or at least did do so at a time.

**Comment by ReneSci** [comment]
Microsoft names the file:  SMS Agent Host service (CcmExec.exe)
Our work computers are managed quite severely by our IT department. Is seems like it is not a virus, this service is just not allowed on our computers.
But I can't see how/why wxMaxima should trigger this service.

**Comment by KubaO** [comment]
It doesn’t matter. This is normal “user experience” on Windows. The service is used by Windows itself and various actions can start it, so I’d say we close this one. Nothing we can do about it.
