### ISSUE TITLE
How to create PDF with Unicode

### ISSUE THREAD

**Issue by danielvolinski** [wxMaxima-developers/wxmaxima#1431]
Hi All,

I manage to put a Unicode character ẽ, in the wxMaxima notebook all the calculations seems to work fine but when I want to create a PDF file out of it I get the following error:

```
! Package inputenc Error: Unicode character ẽ (U+1EBD)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.931 ldisplay(lẽ
                   [r]:diff(R,r))\$

```

I tried
\DeclareUnicodeCharacter{1EBD}{\ensuremath{ẽ}}
but MikTex get stuck and does not finish!

Daniel

**Comment by danielvolinski** [comment]
I think I found the solution. I have to write:
\DeclareUnicodeCharacter{1EBD}{\ensuremath{\tilde{e}}}
in the preamble

I found also a very interesting web site: https://graphemica.com/
If you search for a character like "tilde e" you get, among other things, the character:
"latin small letter e with tilde" and his unicode.
Then you can issue the following command in wxMaxima:
unicode("latin small letter e with tilde");
and you get the character. Then you can use cint(%) and get the unicode:

ibase:obase:16.$
unicode("latin small letter e with tilde");cint(%);
unicode("latin small letter e with macron");cint(%);
unicode("latin small letter e with circumflex");cint(%);
unicode("music sharp sign");cint(%);
unicode("music flat sign");cint(%);
unicode("mathematical bold script capital l");cint(%);
ibase:obase:10.$
utf8_to_unicode(string_to_octets("ẽ"));
octets_to_string(unicode_to_utf8(%));

Daniel

**Comment by gunterkoenigsmann** [comment]
The problem I have with unicode is that there are so many thousands of unicode letters - and for each one there are different methods of producing them - which is made worse by lualatex, pdflatex, plain latex and xelatex differ in the methods of supporting them - and I guess that setting the language to greek, for example, involves supporting many unicode characters.

Since much has changed in this respect in the last few years ad many users still use old latex distributions (all debian-based systems, for example) I am quite afraid of touching this theme...

**Comment by danielvolinski** [comment]
Hi Gunter,
I understand. Right now it is enough for me to have Latin letters with some modification that is reflected in LaTeX. e.g.:
unicode("latin small letter a with tilde") => "ã", point code "00E3" which is written in LaTeX as \tilde{a}.
unicode("latin small letter a with macron") => "ā", point code "0101" which is written in LaTeX as \bar{a}.
unicode("latin small letter a with circumflex") => "â", point code "00E2" which is written in LaTeX as \hat{a}.
unicode("latin small letter a with caron") => "ǎ", point code "01CE " which is written in LaTeX as \check{a}.

This way, I can see the character correctly in the wxMaxima Notebook and also translate it correctly in its corresponding PDF.
I was able to do this by using the following commands in the LaTeX file:
\DeclareUnicodeCharacter{00E3}{\ensuremath{\tilde{a}}}\DeclareUnicodeCharacter{0101}{\ensuremath{\bar{a}}}\DeclareUnicodeCharacter{00E2}{\ensuremath{\hat{a}}}\DeclareUnicodeCharacter{01CE}{\ensuremath{\check{a}}}
This is working right now so there is no need for any modifications in wxMaxima,
Daniel Volinski.
    En martes, 17 de noviembre de 2020 15:30:54 GMT+2, Gunter Königsman <notifications@github.com> escribió:  
 
 


The problem I have with unicode is that there are so many thousands of unicode letters - and for each one there are different methods of producing them - which is made worse by lualatex, pdflatex, plain latex and xelatex differ in the methods of supporting them - and I guess that setting the language to greek, for example, involves supporting many unicode characters.

Since much has changed in this respect in the last few years ad many users still use old latex distributions (all debian-based systems, for example) I am quite afraid of touching this theme...

**Comment by KubaO** [comment]
This is not supportable at all this way - you're free to use local workarounds, but none of this can be merged into wxMaxima, since it'll be entirely useless to everyone else (they'll need "yet another one").

You need to use a variant of LaTeX that natively supports Unicode characters. Such things exist, so I'm closing this as a wontfix - there's truly no way to implement this correctly.
