### ISSUE TITLE
Issues with OMP (takes all cores in idle and crashes after a while)

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1477]
Testing on Mac I still (after fixing #1474) see substantial issues when OMP is enabled:

- wxMaxima takes all cores of my CPU (~1550% CPU load) waiting on input - it is responsive but eats a lot of power doing nothing
- it crashes after a while sitting there and waiting for input

With OMP disabled, both issues are not there - the load is < 5% in idle and it does not crash.

Since I don't see noticeable speed improvements with OMP enabled I wonder if enabling OMP is just a relict from the old days before the substantial speed optimizations last year. What is the recommendation of the developers? Should one try to fix the OMP version or simply disable OMP support e.g. in MacPorts?

**Comment by MSoegtropIMC** [comment]
@miccal: FYI

**Comment by gunterkoenigsmann** [comment]
OMP is used only in very few places:

- Compiling the list of keyword in the maxima manual can require a few minutes of time, at least on the half-way fast MS Windows machine I tried it on => this needs to be done in the background, perhaps. After the first run the list of keywords is loaded from disk until the next maxima update.
- Loading images with Megabytes of gnuplot data might require a few seconds of time - which felt slow if there were animations with 100 frames or similar.
- Compiling the list of autocompletion keywords takes long and tends to happen in the middle of the maxima session.

Does the branch feature/KoenGu/NoBackgroundImageLoad resolve this problem?

**Comment by gunterkoenigsmann** [comment]
Background: if not loading images and gnuplot sources in the background resolves the problem we no more do anything that could possibly create more tasks than we have CPUs at hand and the idea @KubaO had of replacing OMP by std::thread would be way easier to implement.

**Comment by MSoegtropIMC** [comment]
Indeed OMP is more optimized for massive short time threading than stuff which takes a few seconds. Is there a reason why you didn't consider wxWidgets worker threads? I use these in one of my apps and it works well. I think in a wxWidgets based application this might be more natural than std::threads.

**Comment by gunterkoenigsmann** [comment]
Unfortunately wxWidgets doesn't support creating threads. It just has a class you can derive the class containing your threads from so they kind of look like being wxWidgets objects.
And worker threads is what I tried to create using OMP. When opening a file containing plots I need even up to 3 threads per file. OMP is very handy in this case as it automatically detects if we need more threads than we have CPUs at hand and instead of spawning all threads at once creates a queue of threads that are automatically spawned when CPUs are available for doing so.

@KubaO has proposed to use std::thread instead and for everything but the massive multithreading task of loading images in the background I think I have an idea on how to do so. Loading images in the background seems to crash somewhere in wxFilesystem on mac systems. wxFilesystem isn't completely thread-save on linux, neither => disabled that ability for mow. My guess is that after switching everything we can to std::thread I'll have to look if I can first load everything I need and then use threads in order to interpret that data.

**Comment by MSoegtropIMC** [comment]
> Unfortunately wxWidgets doesn't support creating threads.

At least on Windows `wxThread` does create an OS thread - I can e.g. see them in the debugger thread view in MSVC. Many years ago (20?) I wrote an application to control toy robots which heavily uses wxThread, so I am quite sure it has been like this since then (the application is still maintained). I can't say much about other OSes, but I would find it hard to believe that this would work better on Windows than on macOS/Linux. Maybe there is some misunderstanding?

The file system should be 100% thread safe. What is not thread safe in wxWidgets is any interaction with UI, notably updating status bars or the like. This has to be done by sending messages to the main thread (sending messages is thread safe).

As I said, I have quite some experience with heavily multi threaded wxWidgets apps, so I am sure we can sort this out together.

**Comment by gunterkoenigsmann** [comment]
Ok... ...commit 6f63df05923911968ce78ad40f896b10ba4ea3a3 should replace openMP by C++11 methods - that hopefully are more compatible between platforms.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : thanks - I will do a master test build and see.

Btw.: the version without OMP does work fine - I tested it for one week in daily work and to me it looks like the best wxMaxima ever :-)
