### ISSUE TITLE
How to configure context-sensitive help?

### ISSUE THREAD

**Issue by tigran123** [wxMaxima-developers/wxmaxima#1508]
I have just now compiled Maxima 5.44.0 and wxMaxima 21.01.0 from sources (on Ubuntu 18) and the context-sensitive help (F1) does not work.

UPDATE: I edited the line in `~/.wxMaxima` to look like this:

```
helpFile=/usr/local/share/maxima/5.44.0/doc/html/header.hhp
```

But the context-sensitive help (F1) still doesn't work for some reason...

**Comment by daute** [comment]
[It's better to report different - probably not related - problems as different issues]

Concerning issue (2) - on Linux/Unix - the problem seems to be, that the key "F1" does not call the help? So (to provide a fast - but not very comfortable - solution):if you type for example
`integrate`
and select the menu "Help->Context sensitive help" you get the expected help entry (no modification of `./.wxMaxima` required)?

[I will try to find the solution in the next days, it is probably not easy, because the behaviour is different on Windows, but if I remember correctly, I tried to repair it some time ago].

Best regards, Wolfgang

**Comment by tigran123** [comment]
If I go via menu (instead of F1), then it opens the file `/usr/local/share/maxima/5.44.0/doc/html/header.hhp` and displays its content in a separate window:

```
[OPTIONS]
Compatibility=1.1
Contents file=contents.hhc
Index file=index.hhk
Display compile progress=No
Title=Maxima manual
Default topic=maxima_1.html
```

**Comment by daute** [comment]
Please remove your change in `./~wxMaxima` or let it point to the `maxima_singlepage.html` documentation, for example (don't know where the file is exactly on your system):

`helpFile=/usr/local/share/maxima/5.44.0/doc/html/maxima_singlepage.html`

**Comment by tigran123** [comment]
Thank you -- excellent, we are almost there! Yes, after removing the line `helpFile=` from `~/.wxMaxima` AND going via menu it opens a new tab in the browser with the "maxima_singlepage.html#integrate", which causes a jump to the appropriate place in it, i.e. the section with "integrate" explained.

Now, the remaining problem -- why pressing F1 doesn't work?

**Comment by daute** [comment]
@gunterkoenigsmann reported this problem 6(!) years ago in the wxwidgets bug tracker: http://trac.wxwidgets.org/ticket/16788
So it seems, that it never worked.

I tried now to change it to another accelerator key (maybe F1 is 'special'), that did not work, but I found a very strange behavior:
Other keys like F11 (full screen) or F10 (menu) work, if one is **between** some cells (with the 'horizontal cursor' show), but do not work, if one is for example in a title or math cell and entering some text.
And that may be the cause of the problem, because if you want the context sensitive help for a mathematical function (and use F1 to get the help for the function, where the cursor is now), one **is** entering something **inside** a math cell.
Strange...

**Comment by tigran123** [comment]
I would like to add some information that may be useful. I wanted to access that menu entry without F1, but using the keyboard. So I pressed `Alt-H` followed by `ENTER`, but the problem is that it inserts `h` at the cursor position, so the cell content is now `integrahte` instead of `integrate`. And also it opens the wrong anchor of the help file, namely `file:///usr/local/share/maxima/5.44.0/doc/html/maxima_singlepage.html#Function-and-Variable-Index`

**Comment by tigran123** [comment]
Btw, `F11` works anyway, without your today's commit -- i.e. it switches to full screen with no problem.

**Comment by tigran123** [comment]
Thank you, I will try to recompile wxMaxima with this change of yours and see what happens. I will report the result.

**Comment by tigran123** [comment]
Excellent, it works! Thank you very much, Wolfgang, I confirm that both F1 and F11 now work fully as expected. Closing the issue.
PS. Probably like many others, I started with Maxima many years, but the GUI interface of Wolfram Mathematica was more powerful than wxMaxima (or xmaxima) at the time, so I "defected" to Mathematica. But now wxMaxima is extremely powerful and flexible and so I came back to it. Thank you again for your hard work!

**Comment by daute** [comment]
> the cell content is now `integrahte` instead of `integrate`. And also it opens the wrong anchor of the help file, namely `file:///usr/local/share/maxima/5.44.0/doc/html/maxima_singlepage.html#Function-and-Variable-Index`

Remark: That is not the wrong anchor, that is correct behaviour: If the keyword is unknown (and `integrahte` is not a valid keyword!), the index is shown instead.

**Comment by tigran123** [comment]
Yes, thank you, understood. (I always admired German ultimate accuracy :)
