### ISSUE TITLE
XML parsing error when running maximima test suite

### ISSUE THREAD

**Issue by beew** [wxMaxima-developers/wxmaxima#1556]
When I run maxima's testsuite in wxmaxima with the command

run_testsuite(display_all = true), wxmaxima's window freezes and after a while a popup appears that says
```
XML parsing error:'not well formed (invalid token) at line 15'

```

I ran the testsuite in xmaxima and all tests passed.

wxmaxima 21.05.2, maxima 5.45.0, OS is Ubuntu 20.04.

I compiled both maxima and wxmaxima from source and in both cases make check (or make test) passed 100%.

**Comment by daute** [comment]
Strange. Thanks for the bug report. I can reproduce it here. Just calling `run_testsuite();` works, but not with the parameter `display_all = true`. Maybe @gunterkoenigsmann has an idea, how to find the bug - I don't...

**Comment by gunterkoenigsmann** [comment]
I cannot reproduce this one => seems like the offending string is system-specific.

Sometimes with lots of luck one can find the offending portion of XML in the XML monitor: any XML editor should complain about the invalid part. My guess is that `wxmathml.lisp` fails to quote a string for XML which only becomes visible if the quoting actually changes anything.

**Comment by beew** [comment]
Still same error in Wxmaxima 21.11.0, but the line number changed.
```
XML parsing error:'not well formed (invalid token) at line 86
```
and WxMaxima remains frozen after the error popped up and test finished.

OS Ubuntu 20.04, Maxima 5.45.0

**Comment by beew** [comment]
This problem still exists for wxmaxima 21.1.2.0

Now on Ubuntu 22.04.  I wonder if this has to do with maxima is compiled with sbcl?

Again test suite ran with no problem in xmaxima.

**Comment by daute** [comment]
Hey, that was not easy to find. First I thought, it must be an issue with the XML which Maxima generates. But that was wrong. 
The bug occured when running
`run_testsuite(display_all=true,tests="rtest15");`
but not immediately after that command, but after some minutes. If running the complete testsuite it seemed, that the cause was the running testsuite command.
It was **not** triggered by the XML generated by Maxima, but the "autosave"-function - the generated XML there was wrong and it was checked back using wxWidgets before it was written to the disk, which caused the problem.

I got a backtrace when running gdb:
~~~
Thread 1 "wxmaxima" received signal SIGINT, Interrupt.
0x00007ffff6ce299f in __GI___poll (fds=0x5555575f0890, nfds=6, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6ce299f in __GI___poll (fds=0x5555575f0890, nfds=6, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff5f6536e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5f656f3 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff64f02e7 in gtk_dialog_run () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff7775d1a in wxMessageDialog::ShowModal() () at /usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#5  0x00007ffff76bc550 in wxMessageBox(wxString const&, wxString const&, long, wxWindow*, int, int) () at /usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#6  0x00007ffff7919d47 in wxLogGui::Flush() () at /usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#7  0x00005555556ecd3d in ErrorRedirector::DoLogRecord(unsigned long, wxString const&, wxLogRecordInfo const&)
    (this=0x5555560886e8, level=1, msg=..., info=...) at /home/dauti/Software/wxmaxima/src/ErrorRedirector.cpp:85
#8  0x00007ffff7258417 in wxLog::CallDoLogNow(unsigned long, wxString const&, wxLogRecordInfo const&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#9  0x00007ffff7259122 in wxLog::OnLog(unsigned long, wxString const&, wxLogRecordInfo const&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#10 0x00007ffff7450356 in  () at /usr/lib/x86_64-linux-gnu/libwx_baseu_xml-3.0.so.0
#11 0x00007ffff744dce8 in wxXmlDocument::Load(wxInputStream&, wxString const&, int) () at /usr/lib/x86_64-linux-gnu/libwx_baseu_xml-3.0.so.0
#12 0x00005555557c352c in Worksheet::ExportToWXMX(wxString const&, bool) (this=0x5555561ac020, file=..., markAsSaved=true)
    at /home/dauti/Software/wxmaxima/src/Worksheet.cpp:6087
#13 0x0000555555820e8a in wxMaxima::AutoSave() (this=0x55555604bd30) at /home/dauti/Software/wxmaxima/src/wxMaxima.cpp:5743
#14 0x0000555555820c46 in wxMaxima::OnTimerEvent(wxTimerEvent&) (this=0x55555604bd30, event=...) at /home/dauti/Software/wxmaxima/src/wxMaxima.cpp:5723
~~~

And in Worksheet.cpp (around line 6087) we did the check:
~~~
// Let wxWidgets test if the document can be read again by the XML
 // parser before the user finds out the hard way.
          {
            wxXmlDocument doc;
            {
              wxMemoryOutputStream ostream;
              wxTextOutputStream txtstrm(ostream);
              txtstrm.WriteString(xmlText);
              wxMemoryInputStream istream(ostream);
              doc.Load(istream);
            }
~~~

That failed, the generated XML contained something like:
`<sm type=" breakline="true"sum">`
which is of course not valid XML...
