### ISSUE TITLE
Maxima Not Using All Of available CPU

### ISSUE THREAD

**Issue by Some-Person-That-Codes** [wxMaxima-developers/wxmaxima#1568]
![image](https://user-images.githubusercontent.com/86519132/126067622-b6c4d53f-d956-46c9-9e01-6e1898e5c73e.png)
This Image shows that sbcl which does the calculation doesn't utilise all the CPU.
Can you allow the user to select an option (Preferably in the Maxima tab) that allows maxima to use all available threads?
Thanks

**Comment by daute** [comment]
As you wrote, **Maxima** - the program, which does the mathematics in the background - does not more cores. It is written in common lisp and has a long history (where multithreading was not usual).
You can find more information about Maxima at https://maxima.sourceforge.io/
Maxima has it's own bug tracker: https://sourceforge.net/p/maxima/bugs/

wxMaxima (the graphical user interface) uses multithreading (but does usually not need much CPU  compared to Maxima).

If you want to use more CPUs for Maxima, you can run multiple Maxima sessions at one time and do different calculations.

Closing the issue, since it is not a wxMaxima issue.

Best regards, Wolfgang
