### ISSUE TITLE
cmake 3.21.3 error

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1605]
Currently when trying to compile wxMaxima I get a cmake error:
````
CMake Error at info/CMakeLists.txt:9 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
````

**Comment by daute** [comment]
Works here with that CMake version. What is the output of: `pandoc --version`
(It does work here with the latest pandoc release 2.16.1 and that one included in Ubuntu 20.04, but maybe the regex must be adjusted, if `pandoc --version` reports some 'alpha', 'beta', 'pre release') or similar version.

**Comment by gunterkoenigsmann** [comment]
I have no pandoc installed.

**Comment by gunterkoenigsmann** [comment]
Seems like that somehow was the cause of the problem: Installed pandoc and now I can compile wxMaxima again.

**Comment by gunterkoenigsmann** [comment]
I think I found how to trigger it:

- Install pandoc
- configure wxMaxima
- build wxMaxima
- uninstall pandoc
- touch CmakeLists.txt
- try to build wxMaxima instead

In this case cmake triggers a reconfigure but doesn't test if any commands cmake uses have been uninstalled in the meantime.

Would be for closing this ticket as it looks like a cmake bug to me - or if not a bug, at least a cmake shortcut that can lead into a dead end.

**Comment by daute** [comment]
According to Gunter, the problem was not related to the CMake version or the wxMaxima code; the reason was, that wxMaxima was configured when pandoc was installed and build when pandoc was no longer installed.
CMake keeps a cache of found packages, so always start with a clean build directory, after some relevant programs were modified (e.g. uninstalled).

Closing that issue.
