### ISSUE TITLE
Wrong function values by wxplot2d() and find_root()

### ISSUE THREAD

**Issue by jjzheng01** [wxMaxima-developers/wxmaxima#1638]
Hi,

I defined a function as 
**f(x):=abs(log(abs(x)^2)+1)-abs(x+1);**
The value at -0.6 is -0.3783487524680186.
However, when I plot this function, explot2d() gives me different value which is around 5.883.
**wxplot2d([f(x)], [x,-1,-0.1])$**
When I tried to find the root of this function, find_root() gives me same wrong value which is 5.883222611119004.
**find_root(f(x), x, -1, -0.6);**
**find_root(f(x), x, -0.6, -0.1);**

Does anyone have any idea about this issue?

Thanks

I attached the Maxima script file below, please remove the extension name txt before open it by wxMaxima.
[wxplot2d_find_root_issue.wxmx.txt](https://github.com/wxMaxima-developers/wxmaxima/files/8303564/wxplot2d_find_root_issue.wxmx.txt)

**Comment by daute** [comment]
Remark: This issue has nothing to do with wxMaxima, the graphical frontend, it is - if you replace `wxplot2d()` by the Maxima function `plot2d()` - a pure Maxima issue.

The 'hint' for the solution you see in the y-axis of the plot. There you see, that Maxima did **not** plot your function `f(x)`, but "simplified" `log(x^n)` to `n * log(x)` before. It did plot the function:
`abs(2*log(x)+1)-abs(x+1)`

Set
`logexpand:false;`
before the plot, so that such a simplification does not occur (and maybe set it back to `true` afterwards). See the help text for the `log()` function (`? log`) for more information.

Best regards, Wolfgang

**Comment by jjzheng01** [comment]
Dear Daute,

Thank you very much for your reply.
I totally understood my the issue. I can get the correct results now.

I will close this issue accordingly.
