### ISSUE TITLE
Suggestion: Optional degree units for trigonometric functions

### ISSUE THREAD

**Issue by FEA-eng** [wxMaxima-developers/wxmaxima#1644]
Currently, trigonometric functions can only operate on radians. An option to use degrees instead would be very useful so that it's not necessary to write:

sind(d):=sin(d*%pi/180)$
cosd(d):=cos(d*%pi/180)$

at the beginning of each session.

**Comment by gunterkoenigsmann** [comment]
wxMaxima tries to be only a graphical user Interface for maxima (https://maxima.sourceforge.net) which does the actual maths. If you want to change how the maths is done I would therefore ask you to file your feature request there. I don't know though, if that wouldn't be a very big change as things that use trigonometric functions internally like the fft package would have to cope with that change.

Will close this to let for wxMaxima, not  because I believe it to be invalid (you aren't the only user that has aksend for this feature), but, because it would have to be implemented in the other project.
