### ISSUE TITLE
trigreduce doesn't work

### ISSUE THREAD

**Issue by gustavklopp** [wxMaxima-developers/wxmaxima#1679]
Trying to get the argument of the product of 2 complex numbers produces the wrong result:

![slika](https://user-images.githubusercontent.com/6438275/169752568-38389466-3e05-4ef4-8077-d4e6b8de2670.png)

So I multiply $3(\cos(\frac{5π}{13}) + i*\sin(\frac{5π}{13})$ by $4(\cos(\frac{7π}{13})+i*\sin(\frac{7π}{13}))$.

The right answer for the argument should be $\frac{12π}{13}$, not $\frac{25π}{13}$.

You can try yourself with this Maxima file that I've joined:
[BUG.zip](https://github.com/wxMaxima-developers/wxmaxima/files/8751825/BUG.zip)

**My version of WxMaxima:** 22.04.0 Maxima version: 5.46.0 (x86_64-unknown-linux-gnu) Maxima compiled using: ECL 21.2.1

**Comment by richardgobeli** [comment]
That seems to be a maxima issue with atan2 switching to atan and atan getting the wrong result larger than pi/2.  The atan2(sin(ang),cos(ang)) switches to atan(sin(ang)/cos(ang)) +pi when the angle is larger than pi/2. but in this case atan does not get a minus angle for (ang -pi) +pi so the result can be ang.
Atan reduces the atan(tan(ang)) directly to ang and the pi does not get subtracted off.
Below atan should have been -6*pi/13 so that adding pi give 7*pi/13 back.
![image](https://user-images.githubusercontent.com/31253976/170802368-8791d12b-385d-448b-83b4-8b2d8687a9c5.png)

**Comment by gustavklopp** [comment]
Thanks! I've posted on the Maxima issue tracker then: https://sourceforge.net/p/maxima/bugs/3981/

**Comment by gunterkoenigsmann** [comment]
Thanks for forwarding the problem to the maxima team! I seem to remember they recently have tried to fix bugs in atan so you might have found one of the side-effects of that fix.
