### ISSUE TITLE
load package does not work

### ISSUE THREAD

**Issue by murakamiriyugi** [wxMaxima-developers/wxmaxima#1777]
Operating System: Mac OS Ventura
Wxmaxima 23.04.0
Maxima 5.46.0
SBCL 2.3.4
Mode of installation: homebrew

Wxmaxima and Maxima works fine except 
the packages cannot be loaded using the
usual load() command; e.g.

load(ctensor);

does 'nothing' with a message '1 cells in 
evaluation queu'. However, loading the
package with the full path works fine; e.g., 

load("/opt/homebrew/Cellar/maxima/5.46.0_12/share/maxima/5.46.0/share/tensor/ctensor.mac");

works without problem. 

Upon testing the accompanying xmaxima,
loading packages works fine so it can be 
a problem on the part of Wxmaxima or
communication between Wxmaxima and
Maxima.

**Comment by gunterkoenigsmann** [comment]
My only guess at this issue is that wxMaxima takes part of the following constellation:

- The path maxima searches for its share packages in is hardcoded in maxima during the configuration stage of the build. My guess (it is only a guess) is now that your instance of maxima was created with that path being relative to "the current directory" - which might have been done in order to make maxima work fine regardless of which directory it actually is installed in. 
- and wxMaxima changes maxima's idea of "the current directory" to be the one the currently-opened file is in, which is necessary if your project wants to load data from the current directory or wants to save data.

If that is true the bug would be in maxima (https://maxima.sourceforge.net), not in wxMaxima.
-

**Comment by murakamiriyugi** [comment]
Loading packages on Maxima now works fine.

Operating System: Mac OS Sonoma
Wxmaxima 23.11.0
Maxima 5.47.0
SBCL 2.3.10
Mode of installation: homebrew

**Comment by daute** [comment]
Closing that issue, [murakamiriyugi](https://github.com/murakamiriyugi), wrote it works now.
