### ISSUE TITLE
Receive error with wxSIGKILL

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1810]
I don't see any output labels.
How are they turned off and on?  I did not find anything in the configuration dialog.

Also, I get this error when shutting wxMaxima down.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/dce966ab-dc68-4496-afaa-8d776b9ae1d4)
build.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/1e48fcc0-8a3c-474f-a50d-c3a33d8f6403)

**Comment by gunterkoenigsmann** [comment]
In theory you should only need to right-click where you expect an output label and tell what you want to see here. Otherwise "Preferences/Worksheet/Show Labels" should be the place to choose what types of labels you want to see. The only other thing of which I know that it can go wrong: On the mac the label color war transparent, by default, for a while and one can, of course, set it to the color of the worksheet background.

**Comment by richardgobeli** [comment]
The nightly build is failing again.

**Comment by richardgobeli** [comment]
I think this is fixed.
