### ISSUE TITLE
plotdf, issue with slider in version 21.05.2

### ISSUE THREAD

**Issue by ggarrigos** [wxMaxima-developers/wxmaxima#1847]
I have installed a recent version of Wxmaxima 21.05.2, and have noticed an issue while using the option "sliders" in "plotdf". Namely, in this new version, when opening a plotdf window with the option "sliders", for some reason the (blue) slider icon has the same location as the (white) box showing the cursor position coordinates (and in fact, is mostly covered by those coordinates; see picture). So one is not able to click on or move the slider button, which misses the main functionality of this option. This did not happen in the earlier versions I used, so I guess it is due to some changes in the plotdf environment introduced lately. Is it possible to fix this, or somehow recover the slider functionality?

Thanks,  G. 

![issue_plotdf_sliders](https://github.com/wxMaxima-developers/wxmaxima/assets/152096320/c2b222f8-2adf-4f59-85ec-7844d0647cac)

**Comment by gunterkoenigsmann** [comment]
That looks exactly like a GUI issue so it sounds logical to report it for wxMaxima, which provides the GUI.
This part of the GUI is borrowed from Xmaxima, though, which is part of the Maxima project (https://maxima.sourceforge.net). Would you be willing to report that issue there?

I will close this issue for wxMaxima, not, because it is no bug (I am sure that it actually is), but because it is the Maxima team that needs to handle it.
