### ISSUE TITLE
HELP ME!!! XML ERROR.  I canot't save my doccument

### ISSUE THREAD

**Issue by Rodripg2002** [wxMaxima-developers/wxmaxima#1867]
HELP PLEASE.  i use this program today for study for my math exam, and i was trying to save my doccument but an Error appears and dont let me save my doccument. I tried rto copy and paste the same infromatiion into another documment but the error instead goes, is still there. it's is: Invalid XML product. The erroneous XML data has not been saved but has been placed on the clipboard so that it can be debugged as much as possible.

How can i save my documment safely. Or how can i fix this error. I know that MAxima its a free software so, anybody can help me. 

Sorry if there was a mistake on my message, im spanish. 
 
Tnx.

**Comment by gunterkoenigsmann** [comment]
You still have the file open? If you have we have many options:

Option 1:
-  try to save the file (which will give you the error message again)
- open a text editor
- Press `Ctrl`+`V`
...and the text editor should contain all XML data that is needed in order to recover your file. Just send it to me and I will try to recover the file and to fix wxMaxima so that error doesn't occur any more. With a bit of luck I even find a way to make wxMaxima find and automatically repair the error on trying to open a file; If you don't want to post the `.txt` file with the XML here just send it to me per mail (any mail sent to peterpall.de will arrive in my inbox). And if you are using MS Windows the corrected version of wxMaxima can be downloaded from https://wolfgang.dautermann.at/maxima/nightlybuild/ the day after the program's code has been corrected.

Option 2:
 - Save the file as a `.wxm` file instead of `.wxmx`: `.wxm` files are way less tested than `.wxmx` - but don't contain XML that can be generated in a faulty way

Option 3: 
 - Choose the menu item `Cell`/`Remove all output` and save the file after doing that: Normally the error is in the 2D maths generated by maxima, not in the text you have typed.

If Option 2 or 3 works I still beg you to give me the XML or a hint on what could trigger the error so I can generate a minimal test case: Once I have a minimal test case I can fix the problem and add it to the automatic tests that are done after each change to wxMaxima's code.  

As I am responsible for a little child and his grandmother who needs much help Option #1 might need a few extra hours...

**Comment by Rodripg2002** [comment]
Hello!! @gunterkoenigsmann, I appreciate your time and your dedication to my problem, I am going to try to solve it in the way you have explained to me, I don't want to give you more work for your personal reasons, so for some very bad reasons I will copy it again and ready to see if the error disappears but yeah , i'll try to do like u told me. Again, thank you very much for your time :D Greetings!!

**Comment by Rodripg2002** [comment]
Perfect, thank You! I save it like .wmx and it works!!
