### ISSUE TITLE
Add the ability to "pop out" a wx graph

### ISSUE THREAD

**Issue by vext01** [wxMaxima-developers/wxmaxima#190]
I often find I want to rotate a graph. This can not be done using the wx\* grpahing functions, but the mouse can be used if one uses the plain old gnuplot graphing. I usually end up locating the graph definition and removing "wx" from the beginning of the graphing function. Eg: 'wxplot3d' becomes 'plot3d'.

Instead, how about a right click (and keybinding) which "pops out" the graph. What this would do, is call gnuplot to draw the graph in a new window where it can be resized and rotated with the mouse.

**Comment by gunterkoenigsmann** [comment]
I personally think the best we can do is to document the difference between wxplot3d and plot3d (as we have already done in the offline manual) and let the user decide if he wants to use embedded or standalone graphs:

 - I agree with Andrej that we can never be completely sure what gnuplot commands maxima would use to make a standalone graphics even if we might have a good guess in most cases: the same plot with a different first line.
 - Gnuplot allows to embed plots in a subwindow so in theory on X-Windows we could actually include standalone windows into our window. But I doubt that wxCanvas actively supports this and that there is a portable way to use this possibilty on Mac an Windows, too.

I therefore would be inclined to close this ticket, probably as "wontfix".

**Comment by dilijev** [comment]
I was thinking something like a button that says pop-out, and then run the command to create a standalone plot. Since the parameters of plot and wxplot functions are the same AFAIK I think this should be reasonably easy to do. 

The nice thing with inline plots is they can be printed and a document can be made. The nice thing about popped out plots is that you can manipulate them better and explore the plot. Sometimes you may want to do both in a session and an easy way to do that would be nice. 

<div>-------- Original message --------</div><div>From: Gunter Königsman <notifications@github.com> </div><div>Date:02/07/2015  1:42 AM  (GMT-06:00) </div><div>To: andrejv/wxmaxima <wxmaxima@noreply.github.com> </div><div>Cc: Doug Ilijev <doug.ilijev@gmail.com> </div><div>Subject: Re: [wxmaxima] Add the ability to "pop out" a wx graph (#190) </div><div>
</div>I personally think the best we can do is to document the difference between wxplot3d and plot3d (as we have already done in the offline manual) and let the user decide if he wants to use embedded or standalone graphs:

I agree with Andrej that we can never be completely sure what gnuplot commands maxima would use to make a standalone graphics even if we might have a good guess in most cases: the same plot with a different first line.
Gnuplot allows to embed plots in a subwindow so in theory on X-Windows we could actually include standalone windows into our window. But I doubt that wxCanvas actively supports this and that there is a portable way to use this possibilty on Mac an Windows, too.
I therefore would be inclined to close this ticket, probably as "wontfix".

**Comment by gunterkoenigsmann** [comment]
> I was thinking something like a button that says pop-out, and then run
> the command to create a standalone plot. Since the parameters of plot
> and wxplot functions are the same AFAIK I think this should be
> reasonably easy to do.
>
They are. But I am afraid that when we take advantage of this fact we will have to explain why popping up the following graphs fails:

        f(x):=sin(x);
        wxdraw2d(explicit(f(x),x,-.1,.1))$
        f(x):=cos(x);
        wxdraw2d(explicit(f(x),x,-.1,.1))$
        kill(f);

If we instead gave maxout.gnuplot a new name each time and kept the files we could in theory replace the first two lines:

        set terminal pngcairo dashed enhanced truecolor  size 500, 300
        set out '/home/gunter/maxout_11.png'

by something like

        gnuplot default term command

but there might be different default terminals for draw and plot, the user might use a terminal different to the default term - and we cannot guarantee that no future maxima version will change more than the first two lines.

Choosing a completely random filename instead of maxout.gnuplot would add a new feature, though: The ability of evaluating two files at the same time. Currently since both instances of wxmaxima write all their temporary data to the same file the results of two parallel runs are sometimes somehow unexpected.
...and we need to catch the case that a user uses pipes for communication between gnuplot and maxima: plot still saves the data in a file in this case. But the file name extension will be different.

This option *should* work in more cases. We could even pop up any frame of a slideshow this way (for draw we would have to define the gnuplot_file_name and data_file_name options). But this option can be easily broken by changing some unimportant-looking things on maxima's side so there is some risk involved here.

Kind regards,

    Gunter.

**Comment by dilijev** [comment]
I think using different file names is a good change to make, regardless of the feature this issue is discussing. I also think we should use a temp directory instead of cluttering the home directory with these files. 

<div>-------- Original message --------</div><div>From: Gunter Königsman <notifications@github.com> </div><div>Date:02/08/2015  12:14 AM  (GMT-06:00) </div><div>To: andrejv/wxmaxima <wxmaxima@noreply.github.com> </div><div>Cc: Doug Ilijev <doug.ilijev@gmail.com> </div><div>Subject: Re: [wxmaxima] Add the ability to "pop out" a wx graph (#190) </div><div>
</div>
> I was thinking something like a button that says pop-out, and then run
> the command to create a standalone plot. Since the parameters of plot
> and wxplot functions are the same AFAIK I think this should be
> reasonably easy to do.
>
They are. But I am afraid that when we take advantage of this fact we will have to explain why popping up the following graphs fails:

f(x):=sin(x);
wxdraw2d(explicit(f(x),x,-.1,.1))$
f(x):=cos(x);
wxdraw2d(explicit(f(x),x,-.1,.1))$
kill(f);

If we instead gave maxout.gnuplot a new name each time and kept the files we could in theory replace the first two lines:

set terminal pngcairo dashed enhanced truecolor size 500, 300
set out '/home/gunter/maxout_11.png'

by something like

gnuplot default term command

but there might be different default terminals for draw and plot, the user might use a terminal different to the default term - and we cannot guarantee that no future maxima version will change more than the first two lines.

Choosing a completely random filename instead of maxout.gnuplot would add a new feature, though: The ability of evaluating two files at the same time. Currently since both instances of wxmaxima write all their temporary data to the same file the results of two parallel runs are sometimes somehow unexpected.
...and we need to catch the case that a user uses pipes for communication between gnuplot and maxima: plot still saves the data in a file in this case. But the file name extension will be different.

This option *should* work in more cases. We could even pop up any frame of a slideshow this way (for draw we would have to define the gnuplot_file_name and data_file_name options). But this option can be easily broken by changing some unimportant-looking things on maxima's side so there is some risk involved here.

Kind regards,

Gunter.
