### ISSUE TITLE
Printing on Windows - transparency issue

### ISSUE THREAD

**Issue by daute** [wxMaxima-developers/wxmaxima#1909]
The new nice sum, product and integration signs are displayed okay. But if one want's to print them (e.g. just print a PDF), they are just black boxes - only on Windows, not on Linux, there everything is okay:
[int-sum-prod.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/14970083/int-sum-prod.pdf)

Seems to be an issue with transparency, there are some similar reports on the web.

Can we use other - non transparent - SVG-signs - just for printing? Inserting
`<rect width="100%" height="100%" fill="white" />`
in the SVGs worked for the integral sign, but not for the sum and prod sign (and I don't see why). And of course it looks strange, if one chooses a non-white worksheet background, so rendering the signs just for printing non transparent would be a solution (the worksheet is printed with a white background, even if one chooses another color).

Best regards, Wolfgang

**Comment by gunterkoenigsmann** [comment]
Am still unsure what can possibly cause this one: The svg files don't seem to differ in any important place and they are interpreted by exactly the same code on MS Windows and on Linux. In the cross-compiled build they even use the same compiler.

Might the problem be that for one svg file the interpreter uses a transparent black background and for the other a transparent white one? As they both are transparent that should not make a difference on any OS that doesn't have a history of not properly supporting transparency in 2024.

Another thing MS Windows isn't good at is supporting different pixel formats (24 bits per pixel, 2 bit per pixel, 32 bits per pixel,...). I once changed the image format for displayed bitmaps for that reason, but in the last few years a few of my .png files have started having a black or white instead of a transparent background seemingly at random...

**Comment by daute** [comment]
There seem to be issues with transparency only on windows, e.g. (not sure, if that applies in our case):
https://github.com/wxWidgets/wxWidgets/issues/23532
Can we 're-render' the int/sum/prod-cells for printing (maybe only on Windows), e.g. with a white background and no transparency?
