### ISSUE TITLE
Some error messages

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1950]
(%o3)	build_info(version="branch_5_47_base_1372_g4afc4ab91",timestamp="2024-09-01 23:50:52",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.4.8",maxima_userdir="C:/Users/xxx/maxima",maxima_tempdir="C:/Users/xxx/AppData/Local/Temp",maxima_objdir="C:/Users/xxxx/maxima/binary/branch_5_47_base_1372_g4afc4ab91/sbcl/2_4_8",maxima_frontend="wxMaxima",maxima_frontend_version="24.08.0_DevelopmentSnapshot_MSW")

At start up, the following message appears - often only once:
![image](https://github.com/user-attachments/assets/25d4032f-fddc-46ea-9b09-cbc5b6edeb3e)

When trying to copy the build_info:
![image](https://github.com/user-attachments/assets/323fe993-4cfe-49fa-8009-99a384af4e8f)

**Comment by daute** [comment]
The first issue was also reported by me (later, I did not remember that bug report) in issue https://github.com/wxMaxima-developers/wxmaxima/issues/1979. Since it contains more information (and the error as text (not graphic) - searchable), I keep my issue open.
The second issue is - I think - identical to https://github.com/wxMaxima-developers/wxmaxima/issues/1964 (and already solved).

Closing that issue.
Best regards, Wolfgang
