### ISSUE TITLE
Empty lines in comments don't get copied

### ISSUE THREAD

**Issue by OliverBehr** [wxMaxima-developers/wxmaxima#574]
Step 1) Add a comment in your WxMaxima document, that consists of several lines that are separated by an empty line.
Step 2) Copy this comment using Strg+C and paste it into the same document or another using Strg+V.

Result) The content of the comment will be copied, but the empty lines will not exist in the pasted text.

Tested in wxMaxima 15.08.1+git (Windows).

**Comment by gunterkoenigsmann** [comment]
On linux this does not seem to happen any more. Do you know if it still happens with the current nightly build on windows?

Thanks a lot,
and kind regards,

    Gunter.

**Comment by KubaO** [comment]
This definitely happens on Windows. Exact keystrokes to reproduce on a fresh session of wxMaxima:

1. Ctrl-1
2. 123<Enter><Enter>456
3. Down_Arrow
4. Shift-Up_Arrow
5. Ctrl-C
6. Down_Arrow
7. Ctrl-V

![screenshot of the result](https://user-images.githubusercontent.com/5444571/87187989-0dd62680-c2bc-11ea-9280-af21a57d7e16.png)

I'm setting it as a blocker, since it is so fundamental.
