### ISSUE TITLE
changing maxima's path might fail if filename contains cyrillic chars

### ISSUE THREAD

**Issue by Self-Perfection** [wxMaxima-developers/wxmaxima#674]
Observed on wxMaxima 15.08.2 on Arch linux.

```
wxMaxima version: 15.8.2
Maxima version: 5.37.3
Maxima build date: 2015-11-12 23:24:57
Host type: x86_64-unknown-linux-gnu
System type: Linux 4.4.1-2-ARCH x86_64
Lisp implementation type: ECL
Lisp implementation version: 16.0.0
```

For instance, file `/tmp/тест/untitled.wxmx` cannot be opened. wxMaxima gives error:

```
./src/common/unichar.cpp(65): assert "Assert failure" failed in ToHi8bit(): character cannot be converted to single byte
```

And crashes. On the contrary `/tmp/test/untitled.wxmx` gets loaded prefectly well.

`*wxm` files with Cyrillic chars in filepath get loaded but wxMaxima does not compute cells in such files.

I found somewhat similar issue #648 which is already resolved, so I tried to install version from git. But git version does not work with paths with cyrillic as well. It does not crash on load, but shows error in cell:

```
Maxima encountered a Lisp error:
 Directory component "тест" found in pathname
Condition of type: FORMAT-ERROR
Error in format: No more arguments.
  Directory component ~S found in pathname~&  ~S~&is not allowed in TRUENAME or DIRECTORY
                                               ^
while processing indirect format string:
  ~?
   ^
Available restarts:
1. (MACSYMA-QUIT) Maxima top-level
Top level in: #<process TOP-LEVEL>.
```

And, uhm, does not work (does not evaluate cells).

**Comment by gunterkoenigsmann** [comment]
Seems like we jumped out of the frying pan into the fire here:

We can now actually open the file but in the next step maxima chokes
when we tell it to set its working directory to the directory of the file.

What I can tell you is that the problem lies in the following function
in wxmathml.lisp not working because the lisp isn't set up to support
unicode:

(defun wx-cd (dir)
  (when $wxchangedir
    (let ((dir (cond ((pathnamep dir) dir)
                     ((stringp dir)
                      (make-pathname :directory (pathname-directory dir)
                                     :device (pathname-device dir)))
                     (t (error "cd(dir): dir must be a string or
pathname.")))))
      (and (xchdir dir) (setf *default-pathname-defaults* dir)
(namestring dir)))))

I assume if you aren't doing any file I/O to the current directory
unchecking "maxima's pwd is path to document" in wxMaxima's
configuration dialogue will work around this. If not I advice you to ask
the maxima-discuss mailing list on maxima.sourceforge.net: if you give
them all this information and your build_info() I think they will find a
solution. For the next official maxima release they have already worked
hard on trying to resolve this issue. Hope they did succeed.

Thanks a lot, and

Kind regards,

 Gunter.

**Comment by KubaO** [comment]
#1336 tracks this now. I shall close this one.
