### ISSUE TITLE
Changing theta to the Greek character

### ISSUE THREAD

**Issue by danielvolinski** [wxMaxima-developers/wxmaxima#769]
The attached wxMaxima file works fine.
But if you change the name theta with the corresponding Greek character,
(twice in the file) and rerun the file (Ctrl-R) then the last command doesn't finish.
[theta.zip](https://github.com/andrejv/wxmaxima/files/478738/theta.zip)

**Comment by gunterkoenigsmann** [comment]
With the current nightly build of wxMaxima and maxima it does finish. But I get differring results. For a theta character I get:

     (%t25)	mcs[4,4,2]=-r*%e^(-2*β)*sin(θ)^2
    (%t26)	mcs[4,4,3]=-cos(θ)*sin(θ)

For a theta [as] letters I get instead:

(%t25)	mcs[4,4,2]=-r*sin(theta)^2*%e^(-2*β)
(%t26)	mcs[4,4,3]=-cos(theta)*sin(theta)

Seems like maxima's tensor package has problems with unicode characters. Never heard of any other package that has problems with unicode so I think the average support level for unicode is still higher than in the average program. I would beg you to report this problem to the maxima project, though, so it can be fixed.

**Comment by gunterkoenigsmann** [comment]
That means: The results differ only in the ordering of the terms -which is understandable: The name of the variables that are ordered have changed => Seems like this is one of the problems that have been fixed since the last official release of wxMaxima. That would be good news. ...or a problem that only occurs on a specific system. That would be bad instead.

**Comment by gunterkoenigsmann** [comment]
Closing this ticket as the problem wasn't unicode handling but that some algorithms maxima uses work differently if the alphabetic sorting order of the variables changes. According to Richard Fateman this is unavoidable, unfortunately.
