### ISSUE TITLE
Prepare evaluation for next cell

### ISSUE THREAD

**Issue by danielvolinski** [wxMaxima-developers/wxmaxima#986]
When I evaluate a cell by doing Shift-Enter I would like the cursor to go immediately to the next cell to be evaluated again by doing Shift-Enter. Right now, in order to evaluate the next cell I have to click on the next cell and only then evaluate it.

Daniel

**Comment by richardgobeli** [comment]
On my windows 10, after executing a line the cursor is between lines.  When entering another shift-enter, it jumps to the next input line.  So you don't need to click the  next cell with the mouse.
Just keep entering shift- enter and it keeps going.

**Comment by danielvolinski** [comment]
Yes, that is true, so there is an extra Shift-Enter. I would like to save that extra Shift-Enter between the cells and go directly from one cell to the next.
Moreover. Page Break does stop this, i.e. it does not continue.
Thanks.

**Comment by KubaO** [comment]
**There is no extra Shift-Enter**. The behavior is perhaps not very intuitive, but Shift-Enter does exactly the same thing whether the cursor is inside a cell or above the cell.

What could be done to improve user experience is to somehow indicate that the cursor "belongs to" the next cell. Right now it's just a line exactly between two cells, but perhaps some sort of a graphical indicator could clearly indicate that the cursor will evaluate the next cell. I'm not sure whether such an indication would be clear enough, and in any case it'd only help once - since when you know this behavior, you know it and that's that.

I'm considering the original report no-repro, and the potential UX enhancement a wontfix, and am closing it.

If this could be explained better in the manual, then a separate issue should be opened with that request.
